// GENERATED by scripts/build_films_manifest.mjs — do not edit by hand.
//
// `loop` is the short silent grid loop that ships with the site. The full film
// is NOT in this repo: 25 minutes of 1080p is ~590 MB, over what GitHub Pages
// should carry and with the longest single film right on git's 100 MB
// per-file block. Full films live on Cloudflare Stream; `streamId` is the UID
// to play in the lightbox and is empty until the upload script has run.
//
// Titles are derived from the client's filenames and are provisional — the
// same caveat as src/data/portfolio.ts.

export type PortfolioFilm = {
  slug: string;
  title: string;
  orientation: "landscape" | "portrait";
  width: number;
  height: number;
  /** Poster frame shown until the loop is in view and buffered. */
  poster: string | null;
  /** Desktop loop; pass through tierSrc() for the 720p/480p mobile encode. */
  loop: string;
  /** Cloudflare Stream UID for the full film. Empty until uploaded. */
  streamId: string;
};

export const PORTFOLIO_FILMS: PortfolioFilm[] = [
  {
    "slug": "3mindperspectivelodha-m",
    "title": "3mindperspective Lodha M",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/3mindperspectivelodha-m.jpg",
    "loop": "/video/portfolio/3mindperspectivelodha-m.mp4",
    "streamId": ""
  },
  {
    "slug": "78-design-lodha",
    "title": "78 Design Lodha",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/78-design-lodha.jpg",
    "loop": "/video/portfolio/78-design-lodha.mp4",
    "streamId": ""
  },
  {
    "slug": "78-design-studiounicot",
    "title": "78 Design Studio Unicot",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/78-design-studiounicot.jpg",
    "loop": "/video/portfolio/78-design-studiounicot.mp4",
    "streamId": ""
  },
  {
    "slug": "adndkalpatru",
    "title": "ADNDKalpatru",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/adndkalpatru.jpg",
    "loop": "/video/portfolio/adndkalpatru.mp4",
    "streamId": ""
  },
  {
    "slug": "bear-space-costhir",
    "title": "Bear Space & Co Sthir",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/bear-space-costhir.jpg",
    "loop": "/video/portfolio/bear-space-costhir.mp4",
    "streamId": ""
  },
  {
    "slug": "elysian-dsgodrej",
    "title": "Elysian DSGodrej",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/elysian-dsgodrej.jpg",
    "loop": "/video/portfolio/elysian-dsgodrej.mp4",
    "streamId": ""
  },
  {
    "slug": "govindhamvinay",
    "title": "Govindham Vinay",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/govindhamvinay.jpg",
    "loop": "/video/portfolio/govindhamvinay.mp4",
    "streamId": ""
  },
  {
    "slug": "hk-architectsparinee-11-west",
    "title": "HK Architects Parinee 11 West",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/hk-architectsparinee-11-west.jpg",
    "loop": "/video/portfolio/hk-architectsparinee-11-west.mp4",
    "streamId": ""
  },
  {
    "slug": "naitik-shahsky-forest-2",
    "title": "Naitik Shah Sky Forest",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/naitik-shahsky-forest-2.jpg",
    "loop": "/video/portfolio/naitik-shahsky-forest-2.mp4",
    "streamId": ""
  },
  {
    "slug": "naksh-design-studio",
    "title": "Naksh Design Studio",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/naksh-design-studio.jpg",
    "loop": "/video/portfolio/naksh-design-studio.mp4",
    "streamId": ""
  },
  {
    "slug": "oberoi-esquire78-design-studio",
    "title": "Oberoi Esquire78 Design Studio",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/oberoi-esquire78-design-studio.jpg",
    "loop": "/video/portfolio/oberoi-esquire78-design-studio.mp4",
    "streamId": ""
  },
  {
    "slug": "oberoidesign-hue",
    "title": "Oberoi Design Hue",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/oberoidesign-hue.jpg",
    "loop": "/video/portfolio/oberoidesign-hue.mp4",
    "streamId": ""
  },
  {
    "slug": "omkarakshar",
    "title": "Omkar Akshar",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/omkarakshar.jpg",
    "loop": "/video/portfolio/omkarakshar.mp4",
    "streamId": ""
  },
  {
    "slug": "prachi-shahbellevue",
    "title": "Prachi Shah Bellevue",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/prachi-shahbellevue.jpg",
    "loop": "/video/portfolio/prachi-shahbellevue.mp4",
    "streamId": ""
  },
  {
    "slug": "prachiborivali",
    "title": "Prachi Borivali",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/prachiborivali.jpg",
    "loop": "/video/portfolio/prachiborivali.mp4",
    "streamId": ""
  },
  {
    "slug": "rashikohinoor-altissimo",
    "title": "Rashi Kohinoor Altissimo",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/rashikohinoor-altissimo.jpg",
    "loop": "/video/portfolio/rashikohinoor-altissimo.mp4",
    "streamId": ""
  },
  {
    "slug": "shrutiandheri",
    "title": "Shruti Andheri",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/shrutiandheri.jpg",
    "loop": "/video/portfolio/shrutiandheri.mp4",
    "streamId": ""
  },
  {
    "slug": "shyam-nivas-monisha-mistry",
    "title": "Shyam Nivas Monisha Mistry",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/shyam-nivas-monisha-mistry.jpg",
    "loop": "/video/portfolio/shyam-nivas-monisha-mistry.mp4",
    "streamId": ""
  },
  {
    "slug": "sky-forestnaitik-shah",
    "title": "Sky Forest Naitik Shah",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/sky-forestnaitik-shah.jpg",
    "loop": "/video/portfolio/sky-forestnaitik-shah.mp4",
    "streamId": ""
  },
  {
    "slug": "sumangalnaksh-ds",
    "title": "Sumangal Naksh DS",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/sumangalnaksh-ds.jpg",
    "loop": "/video/portfolio/sumangalnaksh-ds.mp4",
    "streamId": ""
  },
  {
    "slug": "zrl-designs",
    "title": "ZRL Designs",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/zrl-designs.jpg",
    "loop": "/video/portfolio/zrl-designs.mp4",
    "streamId": ""
  },
  {
    "slug": "zrldadar",
    "title": "ZRLDadar",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/zrldadar.jpg",
    "loop": "/video/portfolio/zrldadar.mp4",
    "streamId": ""
  }
];

/** True while any film still has no Stream UID — the lightbox stays disabled. */
export const FILMS_AWAITING_UPLOAD = true;
