// GENERATED by scripts/build_films_manifest.mjs — do not edit by hand.
//
// `loop` is the short silent grid loop that ships with the site. The full film
// is NOT in this repo: 25 minutes of 1080p is ~590 MB, over what GitHub Pages
// should carry and with the longest single film right on git's 100 MB
// per-file block. Full films live on Cloudflare Stream; `streamId` is the UID
// to play in the lightbox and is empty until the upload script has run.
//
// Titles are derived from the client's filenames and are provisional — the
// same caveat as src/data/portfolio.ts.

export type PortfolioFilm = {
  slug: string;
  title: string;
  orientation: "landscape" | "portrait";
  width: number;
  height: number;
  /** Poster frame shown until the loop is in view and buffered. */
  poster: string | null;
  /** Desktop loop; pass through tierSrc() for the 720p/480p mobile encode. */
  loop: string;
  /** Cloudflare Stream UID for the full film. Empty until uploaded. */
  streamId: string;
};

export const PORTFOLIO_FILMS: PortfolioFilm[] = [
  {
    "slug": "bed-1",
    "title": "Bed 1",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/bed-1.jpg",
    "loop": "/video/portfolio/bed-1.mp4",
    "streamId": ""
  },
  {
    "slug": "bed-3",
    "title": "Bed 3",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/bed-3.jpg",
    "loop": "/video/portfolio/bed-3.mp4",
    "streamId": ""
  },
  {
    "slug": "bedroom-1",
    "title": "Bedroom 1",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/bedroom-1.jpg",
    "loop": "/video/portfolio/bedroom-1.mp4",
    "streamId": ""
  },
  {
    "slug": "bedroom-2",
    "title": "Bedroom 2",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/bedroom-2.jpg",
    "loop": "/video/portfolio/bedroom-2.mp4",
    "streamId": ""
  },
  {
    "slug": "bits-fractions",
    "title": "Bits & Fractions",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/bits-fractions.jpg",
    "loop": "/video/portfolio/bits-fractions.mp4",
    "streamId": ""
  },
  {
    "slug": "convertable-room",
    "title": "Convertable Room",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/convertable-room.jpg",
    "loop": "/video/portfolio/convertable-room.mp4",
    "streamId": ""
  },
  {
    "slug": "dahaus-pria-1st-draft",
    "title": "Dahaus Pria 1st Draft",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/dahaus-pria-1st-draft.jpg",
    "loop": "/video/portfolio/dahaus-pria-1st-draft.mp4",
    "streamId": ""
  },
  {
    "slug": "dining-kitchen-cdh",
    "title": "DINING KITCHEN CDH",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/dining-kitchen-cdh.jpg",
    "loop": "/video/portfolio/dining-kitchen-cdh.mp4",
    "streamId": ""
  },
  {
    "slug": "full-tour",
    "title": "Full Tour",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/full-tour.jpg",
    "loop": "/video/portfolio/full-tour.mp4",
    "streamId": ""
  },
  {
    "slug": "full-video",
    "title": "Full Video",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/full-video.jpg",
    "loop": "/video/portfolio/full-video.mp4",
    "streamId": ""
  },
  {
    "slug": "home-tour-landscape",
    "title": "Home Tour (Landscape)",
    "orientation": "landscape",
    "width": 1280,
    "height": 720,
    "poster": "/img/portfolio-posters/home-tour-landscape.jpg",
    "loop": "/video/portfolio/home-tour-landscape.mp4",
    "streamId": ""
  },
  {
    "slug": "home-tour-portrait",
    "title": "Home Tour Portrait",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/home-tour-portrait.jpg",
    "loop": "/video/portfolio/home-tour-portrait.mp4",
    "streamId": ""
  },
  {
    "slug": "kids-h",
    "title": "Kids H",
    "orientation": "portrait",
    "width": 1280,
    "height": 2422,
    "poster": "/img/portfolio-posters/kids-h.jpg",
    "loop": "/video/portfolio/kids-h.mp4",
    "streamId": ""
  },
  {
    "slug": "kids",
    "title": "Kids",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/kids.jpg",
    "loop": "/video/portfolio/kids.mp4",
    "streamId": ""
  },
  {
    "slug": "kitchen",
    "title": "Kitchen",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/kitchen.jpg",
    "loop": "/video/portfolio/kitchen.mp4",
    "streamId": ""
  },
  {
    "slug": "livin-dinin",
    "title": "Livin Dinin",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/livin-dinin.jpg",
    "loop": "/video/portfolio/livin-dinin.mp4",
    "streamId": ""
  },
  {
    "slug": "living",
    "title": "Living",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/living.jpg",
    "loop": "/video/portfolio/living.mp4",
    "streamId": ""
  },
  {
    "slug": "magic-booth",
    "title": "Magic Booth",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/magic-booth.jpg",
    "loop": "/video/portfolio/magic-booth.mp4",
    "streamId": ""
  },
  {
    "slug": "master",
    "title": "Master",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/master.jpg",
    "loop": "/video/portfolio/master.mp4",
    "streamId": ""
  },
  {
    "slug": "slowmo",
    "title": "Slow Mo",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/slowmo.jpg",
    "loop": "/video/portfolio/slowmo.mp4",
    "streamId": ""
  },
  {
    "slug": "sneak-peek-maneka-lodha-world-view",
    "title": "Sneak Peek Maneka Lodha World View",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/sneak-peek-maneka-lodha-world-view.jpg",
    "loop": "/video/portfolio/sneak-peek-maneka-lodha-world-view.mp4",
    "streamId": ""
  },
  {
    "slug": "teaser",
    "title": "Teaser",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/teaser.jpg",
    "loop": "/video/portfolio/teaser.mp4",
    "streamId": ""
  },
  {
    "slug": "video-2",
    "title": "Video 2",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/video-2.jpg",
    "loop": "/video/portfolio/video-2.mp4",
    "streamId": ""
  },
  {
    "slug": "workspace",
    "title": "Workspace",
    "orientation": "portrait",
    "width": 720,
    "height": 1280,
    "poster": "/img/portfolio-posters/workspace.jpg",
    "loop": "/video/portfolio/workspace.mp4",
    "streamId": ""
  }
];

/** True while any film still has no Stream UID — the lightbox stays disabled. */
export const FILMS_AWAITING_UPLOAD = true;
