// GENERATED by scripts/build_portfolio_images.mjs — do not edit by hand.
//
// Titles are derived from the client's filenames and nobody has confirmed
// which token is the designer, the building, or the location. Treat every one
// of them as provisional until Umesh signs them off; that is what
// PORTFOLIO_NEEDS_REVIEW is for.

export type PortfolioImage = {
  slug: string;
  /** Groups the landscape and portrait shots of one project together. */
  key: string;
  title: string;
  orientation: "landscape" | "portrait";
  width: number;
  height: number;
  /** Rendered widths, ascending — build the srcset from these. */
  widths: number[];
  /** Inline blur-up placeholder. */
  lqip: string;
  /** Path under assets/portfolio, for tracing a tile back to its master. */
  source: string;
};

export type PortfolioProject = {
  key: string;
  title: string;
  slugs: string[];
  /**
   * Cloudflare Stream UID for this project's full film, once uploaded.
   * Populated by scripts/upload_films_to_stream.mjs.
   */
  streamId?: string;
};

export const PORTFOLIO_IMAGES: PortfolioImage[] = [
  {
    "slug": "unattributed-15-l01",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7002,
    "height": 4668,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJZQC7ADdjDEkIREAAP6FDammvCWoZ2pbQcGOy0vxosFOLNSnEpauattmeEZHV/qXe5vIhTWab0qnMgugzrHpzswqLG0AAAA=",
    "source": "photos/landscape/15.jpg"
  },
  {
    "slug": "unattributed-26-l02",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAsAA4BaJQBOgMXr5DT5eaAL51QA/pTVg4EaOR3uKJJs40gPzEIkqGSzxklVbFl5ZP3jbbeCVnAHXPdyRBcOdl71qGaZks5gw0UpvBEXrNABK2RUilPkCYAAAA==",
    "source": "photos/landscape/26.JPG"
  },
  {
    "slug": "unattributed-4-l03",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAsAA4BaJZQCdADWh8S2QAD+yObm9uggMU5b+VmzTvVe3Tr+//JcEVsJ52iyQ2DNguvKfjPGTwq9mv3ugU/hVyAAAA==",
    "source": "photos/landscape/4.jpg"
  },
  {
    "slug": "dsc00155-hdr-l04",
    "key": "DSC00155-HDR",
    "title": "DSC00155 HDR",
    "orientation": "landscape",
    "width": 5988,
    "height": 3992,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAA4BaJbACdAED/J/eqd9AAAD8GA1b8hL0uSKDTcF6b+JGDPV4PyifvbSOoPOFplFycBssc7r/3YQiUSKof+M8OjYdrDZazmqIA1oyaG414r4AAA==",
    "source": "photos/landscape/DSC00155-HDR.jpg"
  },
  {
    "slug": "dsc00180-hdr-l05",
    "key": "DSC00180-HDR",
    "title": "DSC00180 HDR",
    "orientation": "landscape",
    "width": 7002,
    "height": 4448,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAoAA4BaJZACdAD1XqNSbLEAAP7rrp6Qtm5re/aANi4PfKjVSN9INP1jje/rXMnizJzHfn022kxWdBvzizAA2wReiQWP5WQkuxDp7rAAAA==",
    "source": "photos/landscape/DSC00180-HDR.jpg"
  },
  {
    "slug": "dsc00233-hdr-2-enhanced-sr-l06",
    "key": "DSC00233-HDR-2-Enhanced-SR",
    "title": "DSC00233 HDR 2 Enhanced SR",
    "orientation": "landscape",
    "width": 14004,
    "height": 9336,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJQBOgB9ilTXK8zDgAP7l8Wd5OPAkwPfRE6Qwk6JfT+Rqwq8ZVIczhl/ny3xwHH/3laWde3HPNSUx4FRW+fn2q44jbjgJAAA=",
    "source": "photos/landscape/DSC00233-HDR-2-Enhanced-SR.jpeg"
  },
  {
    "slug": "dsc00240-enhanced-nr-l07",
    "key": "DSC00240-Enhanced-NR",
    "title": "DSC00240 Enhanced NR",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAsAA4BaJYwCdADcRxb7igAA/oQPZj6utWdo3NTkz3uAXvzYM88JPZqIYSCX6jYSXjfLQepsUNOHN2s6EFvMLnmdS0C+vGFbIyUWkqAAAA==",
    "source": "photos/landscape/DSC00240-Enhanced-NR.jpeg"
  },
  {
    "slug": "dsc00243-enhanced-nr-l08",
    "key": "DSC00243-Enhanced-NR",
    "title": "DSC00243 Enhanced NR",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAsAA4BaJQBOgCPQP2WYs+QAAP6EC08XSuyCVXMsFen1b3u+gHvMURAcu9Xc234g9CknHB4osRjNHDISwgp3mmCz4KFENItb2Wp0a0fkTx3epwAAAA==",
    "source": "photos/landscape/DSC00243-Enhanced-NR.jpeg"
  },
  {
    "slug": "unattributed-dsc00360-l09",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQAAsAA4BaJYgCdAERB42fCXZ+DAD+J4K1eu4jCyKFmpFOZxAFgcVQ//aIX8DjisaR55BZ0+hvF+xwzFIX5RVThrdbfVilpO/W7+ieKLALAAAA",
    "source": "photos/landscape/DSC00360.jpeg"
  },
  {
    "slug": "unattributed-dsc00414-l10",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6807,
    "height": 4538,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAsAA4BaJQBOj+AC6r66gAD+fK40ux7PpB47hfUR50dtqKNTZxAXOJeycslqFQZGjxe0PNpZboR/BN1VM3Ux+bZo1pTEJs3hROgmmhkdGaAA",
    "source": "photos/landscape/DSC00414.jpeg"
  },
  {
    "slug": "dsc00850-hdr-l11",
    "key": "DSC00850-HDR",
    "title": "DSC00850 HDR",
    "orientation": "landscape",
    "width": 6956,
    "height": 4637,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAsAA4BaJZACdAYuRwWW+yM3PI8AAP2dC6KyJ9K+qZQDJH1X5bk2xZmTG3BttvfmRag8XNF1CD/0cZLDYlFneecY0KyJwVtwQh2n7Thvo8fN5HJiMijRDea1++FtQAA=",
    "source": "photos/landscape/DSC00850-HDR.jpg"
  },
  {
    "slug": "dsc00964-hdr-l12",
    "key": "DSC00964-HDR",
    "title": "DSC00964 HDR",
    "orientation": "landscape",
    "width": 6880,
    "height": 4587,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAsAA4BaJbACdADjcCw4nmCkAP7Sjtwx6mxyFhhLRLMUvuaiqZyuiqF7c8nyVf/XE8VV5WypD3MDyWpCu3YxEkoEGRzzfMi5FxKd1613xrx2EWYQAA==",
    "source": "photos/landscape/DSC00964-HDR.jpg"
  },
  {
    "slug": "unattributed-dsc01293-l13",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAsAA4BaJZQAAsdhURpDDXAA/lWxUe4TcOZf+nb7Ai/hG/GgPBFdK+QFnEFtccwvAVo9VWu0LvrfdpPIUIAA",
    "source": "photos/landscape/DSC01293.jpg"
  },
  {
    "slug": "unattributed-dsc03519-l14",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 5209,
    "height": 3473,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJQBOgBeQor+23iQAAP5DbJWTtEn2+P1P8JJzYSf6urHAD+JoeC5p3JF4AajPSZOSLcn+YaphMM9HQ+YJBnQXYyA3gjRFk4dEOZ72YC44UjhSQAA=",
    "source": "photos/landscape/DSC03519.jpg"
  },
  {
    "slug": "unattributed-dsc05342-l15",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAsAA4BaJQBOgBujUsIMLKoAAP7zU1dZASgyOnehEb/zxieG+sD4qbg/bRPkV+Go4+CWusPmfAVcRtJsEchVRnvqdIHt8fdlkVwJWX3kBjdRQAA=",
    "source": "photos/landscape/DSC05342.jpg"
  },
  {
    "slug": "unattributed-dsc05363-l16",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAsAA4BaJaACdAEVLplXIIcAAP70pIArRNF59b0J5EB5iuzURzVV53ZpEMS+oDjKw4oT30MW8t0dE0FdwWe0xfDBHtnnRQNesHo8nQKdH/bCGAqAAA==",
    "source": "photos/landscape/DSC05363.jpg"
  },
  {
    "slug": "unattributed-gam00001-l17",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAsAA4BaJZwAAo+RMLpRIAD+9msH3nzTnp9juv09lkoaEjeFi5Y086dN9/gM2EkxQK0L7nWSTKZksAkcLaBkFxbgAAAA",
    "source": "photos/landscape/GAM00001.jpg"
  },
  {
    "slug": "unattributed-gam00019-l18",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwAgCdASoQAAsAA4BaJZQCsAYtV29Mqt5NqIwAAP7tmYlu4GS6KqwSMrQ8+dupItFnPGUFXSHJ0KvFp1Mx3WF6kOpCGUVuIh0zMSSWDJVoAAAA",
    "source": "photos/landscape/GAM00019.jpg"
  },
  {
    "slug": "unattributed-gam00025-l19",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAsAA4BaJYwCdAD5MwJPLSI0GAD+1QaFWhvQQCdJhjMkDIBVk9eCTLCUS6J4gXufB7A0SLb1OGpvgz3hTcHjCNnqJm67ISBu25oGAAA=",
    "source": "photos/landscape/GAM00025.jpg"
  },
  {
    "slug": "unattributed-gam00033-l20",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAsAA4BaJQBdgBbCrCxyAAD8r8l/JKHR4qeLeqrFG3WbDEdXOrsaG/NArtn8uZA7TFynMdpPd3dprhykg1Eu6OdqPgJhVF3GYyCBII3wIAAA",
    "source": "photos/landscape/GAM00033.jpg"
  },
  {
    "slug": "unattributed-gam00069-l21",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAsAA4BaJQBdgCKUmXW5TWiSAAD+uB/F8kPxqqHRD8Wx6pjZHSIbZZKazWzFtG7G82K9dqLa4QVGbN8Anhk1OEjdXao6Ebz7P5gAAAA=",
    "source": "photos/landscape/GAM00069.jpg"
  },
  {
    "slug": "unattributed-gam00094-l22",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAsAA4BaJZwAAl0DLlsZ8dAA/bRNqt4fBv1IXdecYdI86YrV9H0aNnwf0GWmHqEu3jaX+T2qt7PEKB8VH37LYVDzqS6nuwCz0QAA",
    "source": "photos/landscape/GAM00094.jpg"
  },
  {
    "slug": "unattributed-gam00115-l23",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAsAA4BaJaQAAbKo4MZNAAD+6zbTsCcJfH8IwCxl8+nXx132qBtwSXYzA0RV+TNX424sjI8ZXzR/8FLlnCTb9S0qe/sQoAA=",
    "source": "photos/landscape/GAM00115.jpg"
  },
  {
    "slug": "unattributed-gam00116-l24",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 3936,
    "height": 2624,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAsAA4BaJZQAAxPGekzI8tAA/vcq3l0jv4V+neYKNa2RYH16zBV+H3Onwk40fJKkH1+xAYGAmruw/AA=",
    "source": "photos/landscape/GAM00116.jpeg"
  },
  {
    "slug": "unattributed-gam00134-l25",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoQAAsAA4BaJYwC7AYsP2tlzQe63AAA/P/LPTS37/5np2QM9MztUZf9XKysKtCEZa81Cwl0x5tGYJ3Evi8UadNvkL4zptCcv37/rHgHpc49YAAA",
    "source": "photos/landscape/GAM00134.jpg"
  },
  {
    "slug": "unattributed-gam00151-l26",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAsAA4BaJZQAD46uLzmKwKU4AAD+0cW45JMd4nVWvL+obqK4cZHLCfjyJzJqV3m3Is2qG/ZFJKkj3hn4gQBb07CQ1CPZhRrtvHGG6mT74QNRHDLTGQAA",
    "source": "photos/landscape/GAM00151.jpg"
  },
  {
    "slug": "unattributed-gam00161-l27",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA4BaJZwAAv+CXKy4hVAAAP4xhBpmvGlnGOpu/r7VaiOlN2zohhRgMagARHsntxVFSCDy2dzLNrj166YkgHCnLB+qJawCgAAA",
    "source": "photos/landscape/GAM00161.jpg"
  },
  {
    "slug": "unattributed-gam00208-l28",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAsAA4BaJZwAAel4+GalAAD+u/Iv+YW1Bki7hFAg5m0tSnH/IbUdeRyqGrtnhId0FNm2KFWODL358yBP8AAA",
    "source": "photos/landscape/GAM00208.jpg"
  },
  {
    "slug": "unattributed-gam00255-l29",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 5063,
    "height": 3307,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAoAA4BaJYwAAuuYXFDIgAD+8/E8cjrZTzUMzdF7RsiS3PipZuEBfWbpEGSmqjcDC2wKQSuiTr9ZAWLZEOdlLeNSQI6h4Ch/2OAA",
    "source": "photos/landscape/GAM00255.jpg"
  },
  {
    "slug": "unattributed-gam00272-l30",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAsAA4BaJYwCw7DxEL45BAAA/u5QLXiTADaefyMEH0p/8OtvTfWr82WR4BnxOn5P63DVpSbUlGa8UM12LCHuErXsK4zmgy29WDe8ASMAAA==",
    "source": "photos/landscape/GAM00272.jpg"
  },
  {
    "slug": "unattributed-gam00275-l31",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAsAA4BaJQBOgCFVmCrZ5AD+6HFvHoVU4fsmYmZ3IeZF4GJsJqDmBsn/PYCYP8kExxrB2n7VENRNYz1Jja7/vLsaqdnHf64nVhS6UAA=",
    "source": "photos/landscape/GAM00275.jpg"
  },
  {
    "slug": "unattributed-gam00283-l32",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 4648,
    "height": 3468,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAwAA4BaJbACdACowWSTAAD+iUk8Lj/7icwcR6cQLwtBPAe02iUwGcSC4Hc/Y944zbJGPhJ4xGJfTwFBU61n19QIBAW+EAA=",
    "source": "photos/landscape/GAM00283.jpg"
  },
  {
    "slug": "unattributed-img-0204-l33",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6949,
    "height": 4531,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAoAA4BaJZACdAEDZnJ/yLCg3AAA/p/lNhX4Xle2xHw/FqBUKNI50sRE5DvVqvtnK4qDHkqHhglLbBudCLZQ+mvAHrQQTMmtPZO2tJD66JbAAMmGAA==",
    "source": "photos/landscape/IMG_0204.JPG"
  },
  {
    "slug": "unattributed-img-0205-l34",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6783,
    "height": 4338,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAoAA4BaJQBWD+AC7O+ZueoAAP7g291VYRGOF4zh4xHCO/cBMvofkHiSdBb2VpB7IgcZfwgh/mSzozASCx7ErO/tDvrqcHwUszWqvjm47SAMCZs0XIk2IAA=",
    "source": "photos/landscape/IMG_0205.JPG"
  },
  {
    "slug": "unattributed-img-0207-l35",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAsAA4BaJQBOgBLs58jQAAD29upgnzt8Nh7h9fpfnm3gNjeSqFsmWu6V+oKfHhrRK6E031VZWC6pJYzw887bE0ke+wAA",
    "source": "photos/landscape/IMG_0207.JPG"
  },
  {
    "slug": "unattributed-img-0209-l36",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA4BaJZACdAD7AyPF2AWwAP2daky1ob1ivlXntdxDTgogAAiMeP02FvWGg7unfgr18XYHVuUSvHUtsMn5WuzARRJ2iK94AAAA",
    "source": "photos/landscape/IMG_0209.JPG"
  },
  {
    "slug": "unattributed-img-0229-l37",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4571,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAoAA4BaJZgCdAELLdN/cAD+76MDJml1DgPHaMrHnCEVi6YmkoLRTRA3HAgiXkRzfr+PN1jPXAekX8/nq2BMubHe4jaI9uaYRIKZprgAAA==",
    "source": "photos/landscape/IMG_0229.JPG"
  },
  {
    "slug": "unattributed-img-0260-l38",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAsAA4BaJZACdADdHA63tLAA/cegd+73lDKwSrF6u4XbpbWtQyAZrljixuLQEcOcULA1xkpcSANRUn7RMhxWs+YzEAAA",
    "source": "photos/landscape/IMG_0260.JPG"
  },
  {
    "slug": "unattributed-img-0263-l39",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoQAAsAA4BaJYgCdAD7ZMOTfTSAAP724NVu/H2uSavjer33REX30S6pnydZtCqNbZf86aGfzdkjUzBiSdIXQAAA",
    "source": "photos/landscape/IMG_0263.JPG"
  },
  {
    "slug": "unattributed-img-0264-l40",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAsAA4BaJQBOgCFEJSwgAAD+JLLCGhBKK38CnlHdAjsX4xM719nmZBBvRqQpHTL00tuH5isYUAAA",
    "source": "photos/landscape/IMG_0264.JPG"
  },
  {
    "slug": "unattributed-img-0267-l41",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAsAA4BaJbACdAD8YupqI0AA/vWdevyqcPLWikA6z4g+tvDG5NB+7kLZJv/SscxpAJuz5OpEG6VLWHiTW7yXyNfHZ8yCuAA=",
    "source": "photos/landscape/IMG_0267.JPG"
  },
  {
    "slug": "unattributed-img-0276-l42",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAsAA4BaJZACdAEDeHfW+gAA/nIPKHn/D5aMhPvt7dxeu+LUecA6Hzqi2XukiwloTXj2RYbvILI1Ji+OalvRZTu8EtSb53xR/SPcuIBrO0kHCDpAMB3KSQAAAA==",
    "source": "photos/landscape/IMG_0276.JPG"
  },
  {
    "slug": "unattributed-img-0303-l43",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAsAA4BaJQBOgCB/feFY4FgAAP7tKgC92vG+VOSiq7LnVXgqtQ4Usi3JzpdPeZ/YnGLJB008/AhYLq7/ngiTbown0vdLFjX5roUC4RKsXVJ436MS3yK8n3tN9gAA",
    "source": "photos/landscape/IMG_0303.JPG"
  },
  {
    "slug": "unattributed-img-0325-l44",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoQAAsAA4BaJbACdADde5/lSmgA/ol+BTWGdSiKm04tSn5QhAWCjU2Te339PdhV5VytShixbqi8SrgZR2tU2Q2CTKb5Rup75/TxzR+IiwqFRrh6HYiWy4BQYWucAAAA",
    "source": "photos/landscape/IMG_0325.JPG"
  },
  {
    "slug": "unattributed-img-0361-l45",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQAAsAA4BaJQBOgCPUDwZMJJvJoAD+grcdc5Txsexk8NEA+dcApgLKjTMFyKaCSDYO/1s8Jv+rG5nH0zom9GdYidqmIzW9LugYig2kkg8BCAfMgQ9QgcgK+GVYR6kQ73ZTMWsjNkAAAA==",
    "source": "photos/landscape/IMG_0361.JPG"
  },
  {
    "slug": "unattributed-img-0363-l46",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAsAA4BaJZgCdACwDeH84AAA/K/xPRPMISnnn8WH+Ywsj0XpDobz5u5hFTRcQJnL0xYDliVPD6ziZVVB1UGNLISf/rzv9IsPUNSAAAA=",
    "source": "photos/landscape/IMG_0363.JPG"
  },
  {
    "slug": "unattributed-img-1879-l47",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABwAgCdASoQAAsAA4BaJZgCdIExgtyAS7PxpkAAAP7vj2MRLeggg2qXEMY50E2LesIfrm86rNpe1HWsMfv9BSwTu+wPb7GYOkDaxJaaL/EfWt/njgLRaRppbAuqisz34V6CDdvRUBEw/ZjzQAA=",
    "source": "photos/landscape/IMG_1879.JPG"
  },
  {
    "slug": "unattributed-img-1891-l48",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoQAAsAA4BaJbACdAEN3bpPXAAA/k+Klaffw0qlJ+dpUKiE5+gCc2qncJCdynesPNPz70zVREF6pljPUE2aT/e/YOnxOMztavUZWllgojbXOY+Yk+V+Fu0jZQCSAAAA",
    "source": "photos/landscape/IMG_1891.JPG"
  },
  {
    "slug": "unattributed-img-2205-l49",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 4608,
    "height": 3072,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAA4BaJZQAAn3LvjOEmNRAQAD+l/hgF7OgtQYfAfWGYEV9Z/Vb1kq6+51yj8ZIi0DndGgNjYZvkhqaC+4q1rQleNip5XpLR5lJdaujG2M4B4AAAA==",
    "source": "photos/landscape/IMG_2205.JPG"
  },
  {
    "slug": "unattributed-img-2469-l50",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAsAA4BaJYgCdADHXOxg6AAA4n4zrUnqTc6H/cwiMajPD5/1hFx3k3EIMJ5r1oU9+3Dpmoy0NnYNqiAV1VHnU78WqtOs5cAAAA==",
    "source": "photos/landscape/IMG_2469.JPG"
  },
  {
    "slug": "unattributed-img-2595-l51",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAsAA4BaJbACdACgxv69WAD+W/4tZ+LXa+GBWHsi1c9f7E+70pC/Uu0lOL7dJ4+zPf9F+lmBkCpAVxojeA0hUYrDe3E602AsDcwOCjVN96cClXpfBa19FwkAAA==",
    "source": "photos/landscape/IMG_2595.JPG"
  },
  {
    "slug": "unattributed-img-4095-l52",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4083,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAA4BaJQBOgCPz9jS/0RJWgAD97Yreyg/ppTuL/znY+oUDVANX61A3yBL4ubz7sw6gsKrC0Ve1z3p50XNzqbk9PEntveWas4ebVtIaVg2II4AAAA==",
    "source": "photos/landscape/IMG_4095.JPG"
  },
  {
    "slug": "unattributed-img-4098-l53",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAsAA4BaJQBOgBjUQmzxwADOMiRQc/77ReCSL9P0eOFFpAqpS7lPCiWmK8skssq5j2lGJFpSwdvxsE8YnTr37V1IX4LMuKOCC3NP5aoxkKRlLeYpD3g9SJuAAA==",
    "source": "photos/landscape/IMG_4098.JPG"
  },
  {
    "slug": "unattributed-img-4155-l54",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAsAA4BaJYwCsAYs3y57F7bXP7WAAP73QFTJH3SqAf45ncU8KviUf7FB155d1DO2nLNILJm+mAT552/mAfk7l+eq1C0sxKK30OmEn01WE7D+o+Cubye33xy0nq2CcAA=",
    "source": "photos/landscape/IMG_4155.JPG"
  },
  {
    "slug": "unattributed-img-4159-l55",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAsAA4BaJYwCdIMggny/0042nhwAAPQNWNZ3OfrJUtAMtyqosj4SL/gHecf7pZ6qhilAq9Ymy+OfMMPZIAT8pZWVGUpHKV7CPUueTk3f3Vf7YTl8dkEdGcWv3kabQAA=",
    "source": "photos/landscape/IMG_4159.JPG"
  },
  {
    "slug": "unattributed-img-4163-l56",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 5925,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoQAAsAA4BaJQBOgBjMsbkNK0AA99/sgR70ZNPs0/8jywZnJ+PJGZGwaFv+yizltOirlBokt+5U54iIzn8Q8LR4U7xmuwuOZQ9Y4HU5ms31NUtYgu8f+S+F+LNG8AAA",
    "source": "photos/landscape/IMG_4163.JPG"
  },
  {
    "slug": "unattributed-img-4164-l57",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoQAAsAA4BaJQBOkCYjGTzlvNjuHAAA4n+p3OuGMsmmSOztAZheb/Qn8tXJIxz1WMyFBRwXAADsvJz9e/BS3RbensnGsD8D96qIa/A8hs52cVdZlMtyZEXfEn6RsyAAAAA=",
    "source": "photos/landscape/IMG_4164.JPG"
  },
  {
    "slug": "unattributed-img-4193-l58",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJaACw7D8tXub/egAAPzIQwWCA+zyv9qru+TQrscsv914cNU3aCc7gZtxahQEqtZKgu5zG1asrrptPh6/9WFWVuRdXt0AO+AoTrH+qWbl7wAAAAA=",
    "source": "photos/landscape/IMG_4193.JPG"
  },
  {
    "slug": "unattributed-gam00048-p01",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZQDE2B4kRTMaAeuyR5arkAD+jUaq2bh0anzC2TCy5w81ly7TNF8Ef76oDdocflAFKPubW5qSr/XQlpGbue6CCeMOw46e6R6xMP79oeP5LLkjzE/V3qzUhBgCp7Qnhj+qjhI9pZzi/ssAEPC+lW9P0iKbMWKAAAA=",
    "source": "photos/portrait/GAM00048.jpg"
  },
  {
    "slug": "unattributed-gam00062-p02",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBACdASoQABgAPu1kqk4ppaQiMAgBMB2JYgAFgBF/iD/a/o7ZHfrdSWEBYAD8XV8bmJrAmuyOIecj6w3kZaJwwlpi2QOu3AA7HcGqayRC0VHNtywXMFcBT+9OtRmsQ95x3kXbL+gJQXR6c5unuyeW79jqpp2SdPqtzXwLCKG50NcBhN9abLb/9qlNALjy2WAaRkqAHqrHt1N3sHQAAA==",
    "source": "photos/portrait/GAM00062.jpg"
  },
  {
    "slug": "unattributed-gam00130-p03",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JZQC7AB09Y+Vk7tVgLCAAAP7ib1oE5ieDrXZrdtOki8aySDSnEQSw3N2uON3szpWAz/PgXDk46wcVomSKQEZDNMM2NQb2htUCfhD7Kewm2OfN7a7J3QSnQrf4XIt8U+ZHcV8AAAA=",
    "source": "photos/portrait/GAM00130.jpg"
  },
  {
    "slug": "unattributed-gam00138-p04",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoQABgAPu1kqk4ppaQiMAgBMB2JZwC/OCDiS/f7pNhoC4AA/mbV5XDbvekrSyRjEfyRSlK6wXxjAj4gfJdTFaocxrX1dFx/u7Ju+aYhN8R7lS70mD4fHVV1gHXxffxbd9stGUYwjfx3IicQkhiB7U90lIWjgT1wMU4rjwCGAXRPrtGgAAA=",
    "source": "photos/portrait/GAM00138.jpg"
  },
  {
    "slug": "unattributed-img-0100-p05",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3907,
    "height": 5844,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYwC7ACPgnJ43wUj8yYhNaagAAPff0frhHBOVdK/JSpwKUXOruOGMnbQn0NMwe5tyM1OWwa1KBkK+vgV3xk4pmPQNTeQGFQcfeQfALSNxvXSlmeEWqWy/1zHbl6THyrur9AZe4jlLiD5B+ZJ6VpCM8L5AvsISYm1V+cHO0XsExUT/S4TpXmMPQBQG+WiJ3TIh3MQsAAA=",
    "source": "photos/portrait/IMG_0100.JPG"
  },
  {
    "slug": "unattributed-img-0102-p06",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZgCdAB9xS4oheVNz55epxQAA/qLOumnUDJc3kfR7CL3G+ltL0DyH96QCSgPqHb98Khgf02u1EuBIEsk63D+T4wyXNgz+D4O0kMlEy+0xbxPcJvLknlajR/QSP6KzsX2kVOvOkTfBeN/WMzgP5R28b87EUdSq0X8LsuElGH+u/nZV++wJ3DqlDU14Xk8AAAA=",
    "source": "photos/portrait/IMG_0102.JPG"
  },
  {
    "slug": "unattributed-img-0111-p07",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JQBWAAx3nh+TTPJYoDx6AAP65/nSdxuInkVBzTXAbn32koactgfrMbgYxzoVYlsKF8N/mE845DaWRQBG4AgCB3T6sIMGz74RI9/b3/zz2zqXcG6coBEhaCAAAAA==",
    "source": "photos/portrait/IMG_0111.JPG"
  },
  {
    "slug": "unattributed-img-0169-p08",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3083,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACQBACdASoQABUAPu1iqU2ppaOiMAgBMB2JQBdkBwj/FSAJTz9erJT2ckEgRgAA/k7pNGxOinlDEqRqITOggUtwaAnKwsJYth5LtL+TI1DZ+KzO9WxoCUu4ARe/LveqTYoE61lMkitGksqXnK+fs+Hslde/jX8vXpXfHN9i8yQG7o4e1TV4gQ1asbFJnGcMYGAAAA==",
    "source": "photos/portrait/IMG_0169.JPG"
  },
  {
    "slug": "unattributed-img-0174-p09",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3739,
    "height": 5734,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAwBACdASoQABkAPu1iqU2ppaOiMAgBMB2JQBOgO6MfLzd8aC3Jvbm6TlAA/Ef6wNY7Adc7YknJbq6ZRNL4umrAjfwGLGSgC4MDZx67Nheqoemddesm3Kg2KZhPAnju5wX1a9n1WAStc5GZ9QPrUYdBrQ9pND2vGSreFAnyYoqO/Kqykrg+fIWDhTUoYzLAvx1tgAAA",
    "source": "photos/portrait/IMG_0174.JPG"
  },
  {
    "slug": "unattributed-img-0181-p10",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3915,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBACdASoQABkAPu1oqk6ppiQiMAgBMB2JYgCdAYxYyTxTM0JMauYwQBZ70AD+w9jev+1fLH9rUEZbBAgL34rg2BmWIhMQ9FuqyocZuqw4IHmwptHMalKgSaIQeivjKz/SezqmZKAPUnOX16pXtdPbMKmmjqXMAyHa5BXyzMK4T3uzqqrrj7rZHHK1rsLSZoPCjOd3m8tPzm41GYfOzxR4Ev82vXX7pjQAAA==",
    "source": "photos/portrait/IMG_0181.JPG"
  },
  {
    "slug": "unattributed-img-0191-p11",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdABpBykvaq9UrtnyAAPetDZrJYhcUayMtJxMIqNZFoQXRM9lvcf4w9j8Q7jqyg+4tj5Izfal8gWshrwu+vBahSj1mAmshHMwJPst2OIsgdIedjR90jlDtTAOfPnJaYrwQUSHIxIsrRTW1ryt0+2wMOAAA",
    "source": "photos/portrait/IMG_0191.JPG"
  },
  {
    "slug": "unattributed-img-0192-p12",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3453,
    "height": 5994,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoQABwAPu1kq04ppaQiMAgBMB2JQBUfbwA1V5FdN1SroYIAAPxdOqIbtmTi/J/YXrnAQGGCri4LZRTWACo1zvcMqZE+WEKLSku+TK584FV8SJUwqUc9ajjE+KWJgLo1zOuXDi3L3BBkJmZKTMZYxY4McJT6YTjcAAA=",
    "source": "photos/portrait/IMG_0192.JPG"
  },
  {
    "slug": "unattributed-img-0211-p13",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4672,
    "height": 7008,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdL1G4ACZ2sUaCnSQPRq5AAO2pVLAUYroIUs/rGlkQJAUiSPpselKJuVIcU9ChOGQzlDsH6IXkMByUDU+GBeuNosQlAXMjvlgqqdPz/k9toVT2e0OQguBN9dsmAiRgAA==",
    "source": "photos/portrait/IMG_0211.JPG"
  },
  {
    "slug": "unattributed-img-0241-p14",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoQABgAPu1kq04ppaQiMAgBMB2JZgCdMoADTrI8d/kMVQbAAP70J9Gf2aq7M++PdeUvpz5qd7WpHNU38xsnFKiWb7LMirUxQ4AgkERlBfgQKrR8svRxRiQAAAA=",
    "source": "photos/portrait/IMG_0241.JPG"
  },
  {
    "slug": "unattributed-img-0250-p15",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3636,
    "height": 5721,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACwBACdASoQABkAPu1iqU2ppaOiMAgBMB2JaACdMoR3Az6j02cJwMkrzpvG77dgAP7l9kjx/36poIWbQ9+gEgOA5+HNuuCgKmazrIGF2rYigh0qnBjaAYTITs5YjpcAx64T3k0B8bW81VFXaGmWikgJlQU37Oe/+L0Mpf0Q6+Ym+GNuNNRwOgCmTFSAAA==",
    "source": "photos/portrait/IMG_0250.JPG"
  },
  {
    "slug": "unattributed-img-0256-p16",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4672,
    "height": 7008,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAADQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYgCdBaglAQh+sBQ54tDaPm05fadfEAD+oMTeRdUjv7EoanwS3jkIAFGRYSbSev9+c5meNX44fNQkuWFObsd5KuKh6ANQAJ5weuKQe7KCdjuI8iMNbkTdWnN7tAfSBi73QwD4JKKdLWCPSOSkeCraKMXN/xVEetUXs0zy5iiVffrBCknaKLkq/F4Pp/AyAAA=",
    "source": "photos/portrait/IMG_0256.JPG"
  },
  {
    "slug": "unattributed-img-0270-p17",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3893,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADQAwCdASoQABkAPu1iqU2ppaOiMAgBMB2JZACw7BIOYIRLfKp00AAA4SPqKETppW0/ZCp11YT46vDCylvUhGoR4t14qPnSp/AqePfmlWJkXgfmysU5tFn+ctmh4aN2czvkwPVFj3JbjlNRcygrv9J+OE0x1sbTUIvxGbuRnGWW3Yut/FUt9nAA",
    "source": "photos/portrait/IMG_0270.JPG"
  },
  {
    "slug": "unattributed-img-0272-p18",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOmUABtUafv8IsQqZZkPLoAAP3jS2XU5zJFmqr7QAI6BANvN/QV5P+Jl3sqMlRxxO0hVQvkX2IMohFIFv+r7f+kefs+moBWGH7EXCrIxQ4mwht2iyu0Uru3f8HK2olxI/Xr+lzWpfgOURaCVPIm2fAQ1mCe0+iOoPad8IpeIUwwy4GEeG/AGkAzgAAA",
    "source": "photos/portrait/IMG_0272.JPG"
  },
  {
    "slug": "unattributed-img-0277-p19",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4672,
    "height": 7008,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdMoACEVGC8qdlvkyY42kAAP5y9+DLULUffSwvKGN/i32bNx5+FhMVr9WIDTrfGYWe5Ay85b/xmQnnecKAyb3EF7EFCumdej2Fo9pX5CdTR860lXraNXk6nLGhWeoHcW/Rz9XNFWumplD0LutxXeMKguOP4fOeiQcD3l/rsPw3ZveRbyedvu2AAA==",
    "source": "photos/portrait/IMG_0277.JPG"
  },
  {
    "slug": "unattributed-img-0287-p20",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOja/gLv9IV28mSXzQ1xmAeZgAA/Z0v2SuTy7EfsTzbZez0Y/wmcRGkFO9pU9iRMhHBdwuyY85aBsaomheZjX+FGxZ27ODQ0tuHJypF2ij1hGuluv6QJ0gnpU0vF/AMnKT9Purv5w/SFMEaVKCtlmaPBUa1WzqvB/bmEeC1lZXLekXeXPs1XI0jivFPnlTwNhJGrAA=",
    "source": "photos/portrait/IMG_0287.JPG"
  },
  {
    "slug": "unattributed-img-0332-p21",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADQAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JYgCdACGRyixD1aPUK7gA/tCiINmsszSFLBf4jNh7pQCrd4lqcBo1TCwwQzfGecA1GecF2roodEH5ebkJnVdZhmhZ+uy5Xqf8QnjAheAOjI1v2bxnmwNbrtWsih7n/auekVK6DtSgS0TClgS4Ww7ez4Wb6QII+IRIAA==",
    "source": "photos/portrait/IMG_0332.JPG"
  },
  {
    "slug": "unattributed-img-0336-p22",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4672,
    "height": 7008,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOmUABGuXKiUkpm7qVQgAD2cKb7ZhFZYGl+cvHkZF4WfVKrIepRxXnC7CUgx2zZTD9sxS5W9GgJCjWdf9m2L7H1IUy5zr//28SjZKB4hTK9IdJ6FW28XB6we1KqR6y2w7z318R+rnVKnYAxaJxkf1FM19gA",
    "source": "photos/portrait/IMG_0336.JPG"
  },
  {
    "slug": "unattributed-img-1068-p23",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZACdMoADKREU6KyPJxn3mYwA/RM8ddc/NJGK+9H63F+37PM44fMz0FM+gJUJddv5wZUBxeclXZ+ZfI4hp5jhc3PhijDoC9RUyD5RDjePCpvqmMacRgTZ5Rn+eroxWv50c5AqiF1G9rM6fdXSgA6/E60ZLCoYpngtj+8ZaQonAAAA",
    "source": "photos/portrait/IMG_1068.JPG"
  },
  {
    "slug": "unattributed-img-1300-p24",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3897,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBACdASoQABkAPu1iqU2ppaOiMAgBMB2JZACw7YwwzpXae260dhsgqLBAAPsF8IQhs2kT2WSRPJ7PZpiLnVbtdJ/1sFaKQAKzOEsS+6BX9BR4Gd26aXKBZL+4KLcq0LAZ1c1jg/ri8grcYNDyekfIPfXVndjc2sTJVV0qbh94q8c0ebLpObWBy9JbbV3+mQHedX+c8UyMB8BebKFKRB4AAAA=",
    "source": "photos/portrait/IMG_1300.JPG"
  },
  {
    "slug": "unattributed-img-1813-p25",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 4628,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwAwCdASoQABIAPu1iqU2ppaOiMAgBMB2JQBOmUGRthrOSGvYCdelUAP7kau/P6K20vP4hX9pBheAdns7iSa7chnuG0rhgaNHIrqP0VdK5y7LgnxQS5OFYjnqIlzBvcVikKsSK6b5/i8zWW4Hpz+345tAD8rVf9T+rF5ljWK5IRixCLAXI0+rOcpqMkko27GxQAA==",
    "source": "photos/portrait/IMG_1813.JPG"
  },
  {
    "slug": "unattributed-img-1814-p26",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZACdABX+be17X5Bo3FGF3JAAziW4MHnwgxqpLGYRCcyXufxthWgplDkpxmBtJEEyDbtyRvNbw96lvy5bddnPxOtOXnqt5YQnBIR5vF2MfxvlE/W0MCBXixTQw965+CgTQ4/MSj9VFU9xdNWaByZZRVVAAA==",
    "source": "photos/portrait/IMG_1814.JPG"
  },
  {
    "slug": "unattributed-img-1815-p27",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdLwAFp9xtX8IW77aqeaAA/ulfoIazEbnrh7gP9NoZ6Z59BHlB4Ey5fYInij6A+QMkzZ87OdxY13QJo+IfJFQcs914q+f7m4uwM9NAG2WXBFzdunNprCe4VK7Ji+Uk+cgWp6A14AAA",
    "source": "photos/portrait/IMG_1815.JPG"
  },
  {
    "slug": "unattributed-img-1896-p28",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOgBFPPhJ/ba/QkJOKLB+AA/ie1KHwPpZkpMIurprctn7HEzSlcLU1psAn7UTkqC7VfXedyMneQ3soC74m52h1eV1q/ZsfT4stMpPnbbx4a21QS5uLw/XlJCbjkHPGnZt/MGntNkjSA60dBdmyQAAA=",
    "source": "photos/portrait/IMG_1896.JPG"
  },
  {
    "slug": "unattributed-img-2144-p29",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3717,
    "height": 5676,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZQDCgCIAX8uwEnNpk7tM2FEgAADxLDtohOtK0hhYWhmLm5Kp856WaAL9TaNZ22b/VmPu1L12sAjO4+zQAfuFS01MX7Hr6xh+bBPwlO0PnrA9vQrU7y+BmbTXUoHEoAA=",
    "source": "photos/portrait/IMG_2144.JPG"
  },
  {
    "slug": "unattributed-img-2155-p30",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBACdASoQABgAPu1oqk6ppiQiMAgBMB2JYgC7ACG7zfFJu3oXe9pp6ewA/vNyZT2rZ9JeQBo9l8m/dgCmkOKAoMfi4d0tOAmkd6Q0Wfi+0LGhPctqd0nSAf7Keuw3aa44GibJ5Nr/sXa9cKqyoLXXhL6Osm6VLHWY4LoRrHxWpU5wljzDpKAA",
    "source": "photos/portrait/IMG_2155.JPG"
  },
  {
    "slug": "unattributed-img-2157-p31",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAwCdASoQABgAPu1krU6ppaSiMAgBMB2JQBWADSv4AsrtkH7gAP78qQiOGKU0ffmXqIpfPxDf9RcvkH19RHzlw7QdoRvVX9/PbCcu2RdGbuRdotaf2raTsQZVPOBgAAA=",
    "source": "photos/portrait/IMG_2157.JPG"
  },
  {
    "slug": "unattributed-img-2175-p32",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBACdASoQABgAPu1kqk4ppaQiMAgBMB2JZQDA3CH/pT8Uo1l2oSL2AAD7h2bWZUCD3ZU9qpZ/ARMxDHXid+VIhNqtDb+W30RAQ9yqk7e0lX5kbbLeIslwasPkv7bXVb8/Mzo2QP2nU/ySXfEB83SRmc1xAskUggyyMwMDcAA=",
    "source": "photos/portrait/IMG_2175.JPG"
  },
  {
    "slug": "unattributed-img-2212-p33",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3829,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADQAwCdASoQABkAPu1iqk2ppaQiMAgBMB2JQA7gAHQZmX9gE9ZbmwAA/lWxzorQnRpYLfo+oBLjUEzTwvOntzlC2Oji1rd00vPN5muPZerrxYJlCw8hmV3tm8S5sTjiPLi+rBdN5rdBCKcIlvDzZtW0PUpIdvGqFfoQ0FmrV1COWDoiNRnTB7J1Vxoix0L76IAAAA==",
    "source": "photos/portrait/IMG_2212.JPG"
  },
  {
    "slug": "unattributed-img-2251-p34",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 2746,
    "height": 3072,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoQABIAPu1iqU2ppaQiMAgBMB2JaQAAW7jBfvSh1TIjAAD+8dpWPZmE6m13M5Q1fIJEjVFjbqn8eBF5gXiTa/rJzIDXetge1N7Mp5Px7t8vzpdPHQwNRGxkeInpNHcHAAA=",
    "source": "photos/portrait/IMG_2251.JPG"
  },
  {
    "slug": "unattributed-img-2257-p35",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwAwCdASoQABgALrV2u12jqampiYC0SgAD5ewiD/O/EjTiEzRp3ssAAP610LrAfi0KBYtvZrGy2FDEI6oMuUiuarZA3V0/9gh/qm2HJwStNEO/6gBKwgBjBFx4nblSmRqc1rJSfLn3zm5J/bleBPetQ7v19V7P5hOJro23h7c8ZyojAAA=",
    "source": "photos/portrait/IMG_2257.JPG"
  },
  {
    "slug": "unattributed-img-2258-p36",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JZwAAW+thH9+YDCV5aTOAAPyP4L/hk/OHHARrPvqc3pMbNkv2f+y1DLNfo6dSkR3tuJrq3bU+y1l7hCp10jpWfreRT/fVFQQ9vj35GnvOvP6q+8eKqAAA",
    "source": "photos/portrait/IMG_2258.JPG"
  },
  {
    "slug": "unattributed-img-2259-p37",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoQABgAPu1mq04ppaQiMAgBMB2JZwAAW+zo/LikxYq+VAbwAP7uelpebV/I+DQZL6uXauwn4tRLEx6tuIki+f0D5hfLdsySHcht8pnme5FE6ezfZT+T7g5P6iXf/SGWEp79KBZX+15IoiE56VgPAAAA",
    "source": "photos/portrait/IMG_2259.JPG"
  },
  {
    "slug": "unattributed-img-2260-p38",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQAwCdASoQABgAPu1mqk2ppaQiMAgBMB2JaQAAO7LkkbnC9/zsiAAA2zdLczzfGvKhg7kEJAINC2OXvymJWXfGLiXLjLYO/HfkKfvajpduXpXX1FTfEEYh+/A6LfGCND8oih6VjMsWHW48VgCYrm2Re7dNdXH35DS5LH2F1x+AAA==",
    "source": "photos/portrait/IMG_2260.JPG"
  },
  {
    "slug": "unattributed-img-2666-p39",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3764,
    "height": 5994,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQAwCdASoQABkAPu1iqU2ppaOiMAgBMB2JZwDImCFN7hV3/YVaGIAA/u/VVUBOf1F2vI53ALUVszjvyhIGIUeXjYJcnvZ3GipFhOd9jB35JV/0xQLcrianV3P0ptGDKlmFz/WLonGyPVa+ZFx8l5RabmOqqHKiSN/70t9pAAA=",
    "source": "photos/portrait/IMG_2666.jpg"
  },
  {
    "slug": "unattributed-img-2669-p40",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABgAPu1iqk2ppaQiMAgBMB2JZwDDNGlfxH8ryp536g+AAAD+/i7H2COV73uyn469Um7dNf4V82ct/CIHKR9yezwbD9Lp1VrFHyp45ZkKW0WOVmtSisbToUXie+1CJTtPzGABQULCyt9yAr855FtvB60PmgAA",
    "source": "photos/portrait/IMG_2669.jpg"
  },
  {
    "slug": "unattributed-img-3068-p41",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JZQDE2B6V6hdEQPlsM+wovAAA/ktVrTSLwl205dweLpDEvNypKLJdXfJ/LaNXPaQYpmlQvy7vBsWEIWOTO1QMlzqlGLpCDbpXpdUImYIEYvCcpWXBLPNx7NmD6+sNlE3P2dk3j9fY/qtIr66NfsKUiIPY1cOePu6dwHW0HeEAC0iJwAA=",
    "source": "photos/portrait/IMG_3068.JPG"
  },
  {
    "slug": "unattributed-img-4195-p42",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAABwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOmUAS2AxQMwDmsnJLv4/u/AAD+14FGWjoPseaioGEorwtQGg6/ffBpVRC4970LEF6AIpJ3jDTOVIAxuMmnA5sQOi4BrvK6Td+sz/HUtP3+Ad7h53EKQOMLiTRJQ2Q7337o8ie8TMvV2QyV0toZ3lqWbumBzulGD0dD1a+en9l8JL6QN13pRySTgBEd9N5nM3IYnAAAAA==",
    "source": "photos/portrait/IMG_4195.JPG"
  },
  {
    "slug": "unattributed-img-4518-p43",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoQABgAPu1iqk4ppaQiMAgBMB2JYgCdMoRwAB7x0uaK7fiktI80APimNmNemKlgoXi7GtEkERWwVPTTlOIngoL+S1Ky+nt5EK1bsIRgrrspIXccZXjDfrm1MufXeLQk/N4vyCTCk0dQwMYAAAA=",
    "source": "photos/portrait/IMG_4518.JPG"
  },
  {
    "slug": "unattributed-img-6167-p44",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAQBACdASoQABgAPu1orU2ppqSiMAgBMB2JZAAD5DoEwtR2Hdx0Xh2AYAD+6n+HC8WDSc0503YEre5XZlMj5bvJHzBp58d7DSv45rzLL/iDwIaTr+17zyEEC+6Sz698UUOfZR1lj/1ZkoyGhl2V8DiWZADeIZlgz1e1P941GY6guDDAKSZ81NyCHuPjubKI3/Y+Y0WE8W5Tj5B5hVgFr7F5ha7kWAAA",
    "source": "photos/portrait/IMG_6167.jpg"
  },
  {
    "slug": "unattributed-img-6174-p45",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAQBACdASoQABgAPu1iqU2ppaQiMAgBMB2JZQDCgYu4yZ5JPA5dOePoIgD+55NCrohyc8zLS2z+L8Je5pTHjNTI+iLsG/m5fVKNgccxnBimlIvPjwK7UWEqbocd9jSi998t0lzJYZjWgyy0p9aCko9JANbfn8K10ttIhYloBImIJGnsRV/fJTGXtObqqHG0hbFRtbB3Yegc+AK/UxZacAAA",
    "source": "photos/portrait/IMG_6174.jpg"
  },
  {
    "slug": "unattributed-img-6187-p46",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZwC2yywTmotwemZaqeY34moDumwAAP7UvtonPt1V2aNVlddeg5C8ohc8ZLnAYcse17KIUUKLjvfgN9xXPhf6rZs7BhTMofqCAjokE5n0ulHefx22iO+doyp0L6VCn9SdxTy/gAec49nm7kD39Hjzj1OmBNoXvK4aSUN2l2OFVn00z9trzYiYFrmmYchZASRz4CHgAAA=",
    "source": "photos/portrait/IMG_6187.jpg"
  },
  {
    "slug": "unattributed-img-6209-p47",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JZQDE2CHfwadYGBD8pkb/MAAA/e8czfjWSD1+yV0zmFu0pI1X58YB1RN9ILfss/MzHHDn/L6vA9Ck+e8R+NgtbH3vvpc09GRnN4ZHhyMkkYA3gAAAAA==",
    "source": "photos/portrait/IMG_6209.jpg"
  },
  {
    "slug": "unattributed-img-6255-p48",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQAwCdASoQABgAPu1kq04ppaQiMAgBMB2JZQAAW5ayjexTYAD+7U54a2I0ExBuiUzzb2Qg4oWnOFfC9XghFmnfUOU7s5ISj5fOC4XwjoA83P3kGmAnmb8/WegFXUvEouH/4xCAfJD19jaDoByEn9bHIF9ORbkObfFUeygYElw3sDLaP4n/OA7AAAA=",
    "source": "photos/portrait/IMG_6255.jpg"
  },
  {
    "slug": "unattributed-img-6262-p49",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoQABgAPu1iqU2ppaQiMAgBMB2JZQAAQdWwvtnHslR3sBGIAP7YKf5OVMv6A5/vn3a8FZycmdTyaajx9I8cnjxO/KizCdfQt9sNG2pEp/xSlvka+539q4duu/heLdT7yXvER+W6PR3sWLyqy7V32DaTNgIHJOndojdI6Q+I/+zwH2C79XI0FpK/vCbqud4+FwAAAA==",
    "source": "photos/portrait/IMG_6262.jpg"
  },
  {
    "slug": "unattributed-img-6286-p50",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABgAPu1kqU4ppaOiMAgBMB2JQBOgBC2Awu+XL9E1bgjmsAD+yCmpWTUv2fZlIXL8/FZ4etkxgAW7mER4e7p7auqPasLsfUWRU049cXeNa6CF9pGUDUlJ+cOUHdhl4Hhj81zluHrN5sp8cWxdiSA61LFyAAAA",
    "source": "photos/portrait/IMG_6286.jpg"
  },
  {
    "slug": "unattributed-img-6295-p51",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3842,
    "height": 5763,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQAwCdASoQABgAPu1iqk2ppaQiMAgBMB2JQBgbg0XqQZDQ3R1ctEAA/pQ2dPCplybbjQ2/HYnSDEgAmwkjfUif8JnlIlUvllAOQV8qMf/J06AQ/YoMB6a6qI8RPT9paxCMYzM1diGe9VMyfWeAgrQOlGK8+No3SmTzldLh9GXgAA==",
    "source": "photos/portrait/IMG_6295.jpg"
  },
  {
    "slug": "unattributed-img-6301-p52",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAACwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZAC07aglANo4VxsX9mjAecE9KPSgAP7pImbI8QPldAvhTle/oOnj2/Hj35+d/S5OdPHZdPnadbLMxyKs7jhLzXzFxSWeMKNHkZ1KrlPIp6ED2JxKS/lCne5fbdc7PvTYMYngu53D55bvu8/nj2IXhb6jx+FwyukJj/wchkkvdlmIjBe8HP+lloC9hUJtQc14GdB0L9OPCVblF1EJ98rpu+fgAA==",
    "source": "photos/portrait/IMG_6301.jpg"
  },
  {
    "slug": "unattributed-img-6316-p53",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 3584,
    "height": 5376,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdMoRwACm5SHFIn6icvYAA/nDbzL4FMrB1N3O8Zu4XeSUlRJbhC+3XIYVvyODqd3fD2Ns7OhWWxJHp+TOY5fmmLCvmlcrNnvuXBQ0LLTGB83K3gAAA",
    "source": "photos/portrait/IMG_6316.jpg"
  },
  {
    "slug": "unattributed-img-7493-p54",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBACdASoQABgAPu1oqk6ppiQiMAgBMB2JZwDKABjTGnFIBEefsjUVIAD+542eCVe+i1dN8WwD+O6CYcafZsgeLzrjG6TyO66iH5w+EsBtXQms02ojmzjz7pqUfR3jAOHbmnqbX+xe2KVN9cgBG4GhsmDhuwwUAAA=",
    "source": "photos/portrait/IMG_7493.JPG"
  },
  {
    "slug": "unattributed-img-7530-p55",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAAAQBACdASoQABgAPu1kqk2ppaQiMAgBMB2JZQAAW+u3F3F/Mp+2j7w+YAD+8dyJhtwGa9lKJrkpkl0cT67nFYmlLCA1auWdUHDDzzKQd+dUA/cBvY+dd1ot9VaByEVo24eaxlbj5nnvCFmeTG5JwZTGmRK3r/P+x/MNVZt125ft0g6C9xiMPpd5Y7KBUQKORLv98p9AAAA=",
    "source": "photos/portrait/IMG_7530.JPG"
  },
  {
    "slug": "unattributed-img-7540-p56",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoQABgAPu1kqk2ppaQiMAgBMB2JZwDG9Yua36zpuIREu7HKTN1gAP6vCckdNRKI7yhOpKXA9jwftp0GZ2V4qR/ANsFOoi/Pxb16OkFmh6jtPWBU57DAVZXSTtr+O+7EGitdQRlI51QKbndY76mqXdSgXEO1pRsYJjwBEp7Nm3zpezi3rAAAAA==",
    "source": "photos/portrait/IMG_7540.JPG"
  }
];

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    "key": "unattributed",
    "title": "Unattributed",
    "slugs": [
      "unattributed-15-l01",
      "unattributed-26-l02",
      "unattributed-4-l03",
      "unattributed-dsc00360-l09",
      "unattributed-dsc00414-l10",
      "unattributed-dsc01293-l13",
      "unattributed-dsc03519-l14",
      "unattributed-dsc05342-l15",
      "unattributed-dsc05363-l16",
      "unattributed-gam00001-l17",
      "unattributed-gam00019-l18",
      "unattributed-gam00025-l19",
      "unattributed-gam00033-l20",
      "unattributed-gam00069-l21",
      "unattributed-gam00094-l22",
      "unattributed-gam00115-l23",
      "unattributed-gam00116-l24",
      "unattributed-gam00134-l25",
      "unattributed-gam00151-l26",
      "unattributed-gam00161-l27",
      "unattributed-gam00208-l28",
      "unattributed-gam00255-l29",
      "unattributed-gam00272-l30",
      "unattributed-gam00275-l31",
      "unattributed-gam00283-l32",
      "unattributed-img-0204-l33",
      "unattributed-img-0205-l34",
      "unattributed-img-0207-l35",
      "unattributed-img-0209-l36",
      "unattributed-img-0229-l37",
      "unattributed-img-0260-l38",
      "unattributed-img-0263-l39",
      "unattributed-img-0264-l40",
      "unattributed-img-0267-l41",
      "unattributed-img-0276-l42",
      "unattributed-img-0303-l43",
      "unattributed-img-0325-l44",
      "unattributed-img-0361-l45",
      "unattributed-img-0363-l46",
      "unattributed-img-1879-l47",
      "unattributed-img-1891-l48",
      "unattributed-img-2205-l49",
      "unattributed-img-2469-l50",
      "unattributed-img-2595-l51",
      "unattributed-img-4095-l52",
      "unattributed-img-4098-l53",
      "unattributed-img-4155-l54",
      "unattributed-img-4159-l55",
      "unattributed-img-4163-l56",
      "unattributed-img-4164-l57",
      "unattributed-img-4193-l58",
      "unattributed-gam00048-p01",
      "unattributed-gam00062-p02",
      "unattributed-gam00130-p03",
      "unattributed-gam00138-p04",
      "unattributed-img-0100-p05",
      "unattributed-img-0102-p06",
      "unattributed-img-0111-p07",
      "unattributed-img-0169-p08",
      "unattributed-img-0174-p09",
      "unattributed-img-0181-p10",
      "unattributed-img-0191-p11",
      "unattributed-img-0192-p12",
      "unattributed-img-0211-p13",
      "unattributed-img-0241-p14",
      "unattributed-img-0250-p15",
      "unattributed-img-0256-p16",
      "unattributed-img-0270-p17",
      "unattributed-img-0272-p18",
      "unattributed-img-0277-p19",
      "unattributed-img-0287-p20",
      "unattributed-img-0332-p21",
      "unattributed-img-0336-p22",
      "unattributed-img-1068-p23",
      "unattributed-img-1300-p24",
      "unattributed-img-1813-p25",
      "unattributed-img-1814-p26",
      "unattributed-img-1815-p27",
      "unattributed-img-1896-p28",
      "unattributed-img-2144-p29",
      "unattributed-img-2155-p30",
      "unattributed-img-2157-p31",
      "unattributed-img-2175-p32",
      "unattributed-img-2212-p33",
      "unattributed-img-2251-p34",
      "unattributed-img-2257-p35",
      "unattributed-img-2258-p36",
      "unattributed-img-2259-p37",
      "unattributed-img-2260-p38",
      "unattributed-img-2666-p39",
      "unattributed-img-2669-p40",
      "unattributed-img-3068-p41",
      "unattributed-img-4195-p42",
      "unattributed-img-4518-p43",
      "unattributed-img-6167-p44",
      "unattributed-img-6174-p45",
      "unattributed-img-6187-p46",
      "unattributed-img-6209-p47",
      "unattributed-img-6255-p48",
      "unattributed-img-6262-p49",
      "unattributed-img-6286-p50",
      "unattributed-img-6295-p51",
      "unattributed-img-6301-p52",
      "unattributed-img-6316-p53",
      "unattributed-img-7493-p54",
      "unattributed-img-7530-p55",
      "unattributed-img-7540-p56"
    ]
  },
  {
    "key": "DSC00155-HDR",
    "title": "DSC00155 HDR",
    "slugs": [
      "dsc00155-hdr-l04"
    ]
  },
  {
    "key": "DSC00180-HDR",
    "title": "DSC00180 HDR",
    "slugs": [
      "dsc00180-hdr-l05"
    ]
  },
  {
    "key": "DSC00233-HDR-2-Enhanced-SR",
    "title": "DSC00233 HDR 2 Enhanced SR",
    "slugs": [
      "dsc00233-hdr-2-enhanced-sr-l06"
    ]
  },
  {
    "key": "DSC00240-Enhanced-NR",
    "title": "DSC00240 Enhanced NR",
    "slugs": [
      "dsc00240-enhanced-nr-l07"
    ]
  },
  {
    "key": "DSC00243-Enhanced-NR",
    "title": "DSC00243 Enhanced NR",
    "slugs": [
      "dsc00243-enhanced-nr-l08"
    ]
  },
  {
    "key": "DSC00850-HDR",
    "title": "DSC00850 HDR",
    "slugs": [
      "dsc00850-hdr-l11"
    ]
  },
  {
    "key": "DSC00964-HDR",
    "title": "DSC00964 HDR",
    "slugs": [
      "dsc00964-hdr-l12"
    ]
  }
];

/** Every derived title is provisional — see the header. */
export const PORTFOLIO_NEEDS_REVIEW = true;
