// GENERATED by scripts/build_portfolio_images.mjs — do not edit by hand.
//
// Titles are derived from the client's filenames and nobody has confirmed
// which token is the designer, the building, or the location. Treat every one
// of them as provisional until Umesh signs them off; that is what
// PORTFOLIO_NEEDS_REVIEW is for.

export type PortfolioImage = {
  slug: string;
  /** Groups the landscape and portrait shots of one project together. */
  key: string;
  title: string;
  orientation: "landscape" | "portrait";
  width: number;
  height: number;
  /** Rendered widths, ascending — build the srcset from these. */
  widths: number[];
  /** Inline blur-up placeholder. */
  lqip: string;
  /** Path under assets/portfolio, for tracing a tile back to its master. */
  source: string;
};

export type PortfolioProject = {
  key: string;
  title: string;
  slugs: string[];
  /**
   * Cloudflare Stream UID for this project's full film, once uploaded.
   * Populated by scripts/upload_films_to_stream.mjs.
   */
  streamId?: string;
};

export const PORTFOLIO_IMAGES: PortfolioImage[] = [
  {
    "slug": "maneka-lodha-world-view-l01",
    "key": "Maneka_Lodha_World_View",
    "title": "Maneka Lodha World View",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAsAA4BaJQBOgCB/feFY4FgAAP7tKgC92vG+VOSiq7LnVXgqtQ4Usi3JzpdPeZ/YnGLJB008/AhYLq7/ngiTbown0vdLFjX5roUC4RKsXVJ436MS3yK8n3tN9gAA",
    "source": "photos/landscape/001_Maneka_Lodha_World_View.jpg"
  },
  {
    "slug": "smridhioberoi-spelnder-l02",
    "key": "SmridhiOberoi_Spelnder",
    "title": "Smridhi Oberoi Spelnder",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAsAA4BaJYwCsAC6DFSRgAD++Rav8HtG1GPc1up1/eJsbpWPsXrsuXYl20xWvM0NxEyCqcO+HAAA",
    "source": "photos/landscape/002_SmridhiOberoi_Spelnder.jpg"
  },
  {
    "slug": "aarshyaatelier-bunglow-lonavla-l03",
    "key": "Aarshyaatelier_Bunglow_Lonavla",
    "title": "Aarshyaatelier Bunglow Lonavla",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAsAA4BaJQBdgCHfK+0O1VAA/vIFoSoN8SkRpjfRp2cT20/ZRGX+X0h+e8s20TZtRJO1aduYpeAK4mEMfNh1ncnIAAAA",
    "source": "photos/landscape/005_Aarshyaatelier_Bunglow_Lonavla.jpg"
  },
  {
    "slug": "sagar-gala-designsghatkopar-2bhk-l04",
    "key": "Sagar_Gala_DesignsGhatkopar_2bhk",
    "title": "Sagar Gala Designs Ghatkopar 2bhk",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJZQCdAEKVj9hxgoAAP7ydRlVkBSBSCg4PCFID3AZuAtVBRQJdXlaCCvWutX3G0RfAAddAebnAxzLg1dQX069I2zNxecSAAA=",
    "source": "photos/landscape/006_Sagar_Gala_DesignsGhatkopar_2bhk.jpg"
  },
  {
    "slug": "clay-house-design2bhk-residential-l05",
    "key": "Clay_House_Design2BHK_residential",
    "title": "Clay House Design2 BHK Residential",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAsAA4BaJZQAD5FQ4OPRUzUAAP4mKTMgWTJJ7oAoVMcZCaFgAMNNdv9Bi4RJjrSzd1LkQ1Ot5L1pR1QMW8cf8/IWJdiQi9NFTAGjHVCbcVvwedpGj0930AVpQOAA",
    "source": "photos/landscape/007_Clay_House_Design2BHK_residential.jpg"
  },
  {
    "slug": "design-hues3bhkthane-l06",
    "key": "Design_hues3bhkThane",
    "title": "Design Hues3bhk Thane",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAsAA4BaJZwAAo+RMLpRIAD+9msH3nzTnp9juv09lkoaEjeFi5Y086dN9/gM2EkxQK0L7nWSTKZksAkcLaBkFxbgAAAA",
    "source": "photos/landscape/008_Design_hues3bhkThane.jpg"
  },
  {
    "slug": "78-designsgirgaon3bhk-l07",
    "key": "78_DesignsGirgaon3bhk",
    "title": "78 Designs Girgaon3bhk",
    "orientation": "landscape",
    "width": 1616,
    "height": 1080,
    "widths": [
      640,
      1280
    ],
    "lqip": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAsAA4BaJYwCdADG/y6HVQAAzjeH8EeS6Fm3F+3d0zBy4zIgnGpz/B41GroayHvpJIqc/WCLt6QKaEbMAA==",
    "source": "photos/landscape/009_78_DesignsGirgaon3bhk.jpg"
  },
  {
    "slug": "kinjallonavla-l08",
    "key": "KinjalLonavla",
    "title": "Kinjal Lonavla",
    "orientation": "landscape",
    "width": 4608,
    "height": 3072,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAA4BaJZQAAn3LvjOEmNRAQAD+l/hgF7OgtQYfAfWGYEV9Z/Vb1kq6+51yj8ZIi0DndGgNjYZvkhqaC+4q1rQleNip5XpLR5lJdaujG2M4B4AAAA==",
    "source": "photos/landscape/010_KinjalLonavla.jpg"
  },
  {
    "slug": "home-maneka-thapar-designs-l09",
    "key": "Home_Maneka_Thapar_Designs",
    "title": "Home Maneka Thapar Designs",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAsAA4BaJagCdAEN2WgGEtgA/uaWkx378zuUi8P1Ev/6DA+Htqb1NbN43o0OckEoDa433QrIVb38kNFCVXq/WpiL0ggiHkquEEqa3SDbibdom2oYe4EkuAAAAA==",
    "source": "photos/landscape/011_Home_Maneka_Thapar_Designs.jpg"
  },
  {
    "slug": "krishikaurvashi-l10",
    "key": "KrishikaUrvashi",
    "title": "Krishika Urvashi",
    "orientation": "landscape",
    "width": 5771,
    "height": 4332,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAwAA4BaJbACdAEUa97mCigAAP4mklzfJD4g7ueW4wmDxShLORd1DsNPF6rplF5H8D6SE4rd5Qnfr7RiF5uBpnyNzu/Q/HwAAA==",
    "source": "photos/landscape/012_KrishikaUrvashi.jpg"
  },
  {
    "slug": "sakshipeppermoney-l11",
    "key": "SakshiPepperMoney",
    "title": "Sakshi Pepper Money",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAsAA4BaJQBOgCGwU37fXIAA/uxbxL+RvNpTAatnr0euR3auKHhUuvRECWOB4Hhscvf64HlXIMRdMjjoz0SN4K/Z41o7eGkIerBDKZNj70vG0gOoLAAA",
    "source": "photos/landscape/013_SakshiPepperMoney.jpg"
  },
  {
    "slug": "omkarsalon-l12",
    "key": "omkarsalon",
    "title": "Omkarsalon",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQAAsAA4BaJYwCsAYuvuFnnNO4O6AA/ut5prFe1sKuWvW8UCPAK4L9Lbx37IMbvPb8Hc1+xDTa4/XkaHcyVXg7VGpYHKmfzF/9+Lo7h1tedqbUZt7UNMSiLgCqQ78G0rEAAA==",
    "source": "photos/landscape/014_omkarsalon.jpg"
  },
  {
    "slug": "claydeepak-jyoti-l13",
    "key": "claydeepak_jyoti",
    "title": "Claydeepak Jyoti",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAsAA4BaJYwC7AEUiaTKOcAA/u3rpaziRRhxtb4cKLhI3s12Zjun4KPq42qAPU+25xa1KSaeluIfezNcmjIMDMZoxjyJwAA=",
    "source": "photos/landscape/015_claydeepak_jyoti.jpg"
  },
  {
    "slug": "bombay-cot78-design-l14",
    "key": "bombay_cot78_Design",
    "title": "Bombay Cot78 Design",
    "orientation": "landscape",
    "width": 1616,
    "height": 1080,
    "widths": [
      640,
      1280
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJZQC7ADjeeW1nL8AAPw6oFLbg801U/gVLKfyo3MVpXhZL3N/elPWJB9UDcoSup0v4xi0n2l3rD7o9F7tA68N74nmJTBKIAA=",
    "source": "photos/landscape/016_bombay_cot78_Design.jpg"
  },
  {
    "slug": "design-hueshome-l15",
    "key": "Design_HuesHome",
    "title": "Design Hues Home",
    "orientation": "landscape",
    "width": 1920,
    "height": 1080,
    "widths": [
      640,
      1280,
      1920
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAkAA4BaJZQC7AYuRCxcij+AAP5p/E+pPFQqVje/dFVk0n88cxkBi+4++r9j6qloAM+8pRkP0lIDuzRyMk6qoGLx1qcjv2uxdr4pELCZQBOngW+AAA==",
    "source": "photos/landscape/017_Design_HuesHome.jpg"
  },
  {
    "slug": "priyadahaus-l16",
    "key": "PriyaDahaus",
    "title": "Priya Dahaus",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAsAA4BaJZQAApywfpNnMQAA/u0ZBOc6NBRDpFfXZCDd0orHNqdJ3y+FHoqBYTmJDw7/XI1dYAAA",
    "source": "photos/landscape/018_PriyaDahaus.jpg"
  },
  {
    "slug": "kea-design-labdahisar-l17",
    "key": "KEA_Design_LabDahisar",
    "title": "KEA Design Lab Dahisar",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAsAA4BaJZQAAeu7wXZ7IAD+iMES488ekUDtaGsEXWAqjO8Bd15pC4HhrjKVUtBgSBj6mWOcufORIpWuYb/8HhvsjNvJYLPdYAAA",
    "source": "photos/landscape/019_KEA_Design_LabDahisar.jpg"
  },
  {
    "slug": "omkar-beaumonte-l18",
    "key": "Omkar_Beaumonte",
    "title": "Omkar Beaumonte",
    "orientation": "landscape",
    "width": 6124,
    "height": 4083,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAA4BaJQBOgCPz9jS/0RJWgAD97Yreyg/ppTuL/znY+oUDVANX61A3yBL4ubz7sw6gsKrC0Ve1z3p50XNzqbk9PEntveWas4ebVtIaVg2II4AAAA==",
    "source": "photos/landscape/020_Omkar_Beaumonte.jpg"
  },
  {
    "slug": "arzoo-jain2bhk-l19",
    "key": "Arzoo_Jain2bhk",
    "title": "Arzoo Jain2bhk",
    "orientation": "landscape",
    "width": 4402,
    "height": 3072,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAwAgCdASoQAAsAA4BaJZwC7AEC2BJ+W17hAAD+alF+Q2PH7msst7CZx/DYew/j/X69jK1mvkHbepCEzE734okAAAA=",
    "source": "photos/landscape/021_Arzoo_Jain2bhk.jpg"
  },
  {
    "slug": "mahimdesign-hive-l20",
    "key": "MahimDesign_Hive",
    "title": "Mahim Design Hive",
    "orientation": "landscape",
    "width": 14004,
    "height": 9336,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJQBOgB9ilTXK8zDgAP7l8Wd5OPAkwPfRE6Qwk6JfT+Rqwq8ZVIczhl/ny3xwHH/3laWde3HPNSUx4FRW+fn2q44jbjgJAAA=",
    "source": "photos/landscape/022_MahimDesign_Hive.jpeg"
  },
  {
    "slug": "omkar2bhk-pune-l21",
    "key": "Omkar2bhk_Pune",
    "title": "Omkar2bhk Pune",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAsAA4BaJYwCdAD2PCqaPgAA/m0hGA9VvunRvfdOyjXyXsNbRoORwcvwv/qUsNHSUHOWSLC/2XkJM9hbAopQU4m7N/9HAAA=",
    "source": "photos/landscape/023_Omkar2bhk_Pune.tif"
  },
  {
    "slug": "omkarpune-office-l22",
    "key": "OmkarPune_Office",
    "title": "Omkar Pune Office",
    "orientation": "landscape",
    "width": 7005,
    "height": 4670,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsAA4BaJQBOgCLVDtcR6D6AAP7dj5I6rZHNPwKOfyapF2IpH/jNKyLDJ0Gjouet7okEbdDAznfyWNJOI/fWb309s+naLiX2kQgfyHIAAA==",
    "source": "photos/landscape/024_OmkarPune_Office.tif"
  },
  {
    "slug": "78-design-studiounicot-l23",
    "key": "78_Design_StudioUnicot",
    "title": "78 Design Studio Unicot",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAsAA4BaJQBOgBozjI2aVgAA/Y8NEE455X4b8oWerl9CPwtIYwSQlDdGF0JGzRhtbL7/qrUALV1n3lOm4sP8nckLzZTE8mNQAAAA",
    "source": "photos/landscape/025_78_Design_StudioUnicot.jpg"
  },
  {
    "slug": "78-design-lodha-l24",
    "key": "78_Design_Lodha",
    "title": "78 Design Lodha",
    "orientation": "landscape",
    "width": 4608,
    "height": 3072,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAsAA4BaJYwCw7EMrMlrsgAA+N2hYUg+nA62WU/VK9N+cTY8QkfdzCrXbq/H0uSnzuROiMhpP9Fd/655Av46sawAAA==",
    "source": "photos/landscape/026_78_Design_Lodha.jpg"
  },
  {
    "slug": "dorityversova-l25",
    "key": "DorityVersova",
    "title": "Dority Versova",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQAAsAA4BaJQBOgCLJ9Wv/zFwAAP7q3EH5VBrrWGFu/YlvdFAywh6v4i9TQFgsxDVZNoxzY0TZCP2bOBPo5hwnUAx1Q/WlpXvgvdDAGwfnF4WOrle5lFHVZUnSkyfhYAA=",
    "source": "photos/landscape/027_DorityVersova.jpg"
  },
  {
    "slug": "naitiklodha-bellisimo-l26",
    "key": "NaitikLodha_Bellisimo",
    "title": "Naitik Lodha Bellisimo",
    "orientation": "landscape",
    "width": 6124,
    "height": 4083,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAQCdASoQAAsAA4BaJQBOgBnx5mPoYAD+wdlFv9vAzzGOV1LXX7BxWejk32kxfv3JhSX8Xs2CtyOi2SBRL4IL7of+rpxDm9S1bMTp/ow+pQYhqW6iqONLvY83sh7AAAA=",
    "source": "photos/landscape/028_NaitikLodha_Bellisimo.jpg"
  },
  {
    "slug": "naitik-shahsky-forest-2-l27",
    "key": "Naitik_ShahSky_Forest_[2]",
    "title": "Naitik Shah Sky Forest",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAsAA4BaJaACdAEOcDKXe5IAAP7vLTVDygp3CR1v2tjwW3iRPIjv/lYxGo1/b8v+zV6Zgea1+AJqE1FbcfFQCa4l1gNTzNsJ43OcypVfqEOyKqbyIiAA",
    "source": "photos/landscape/029_Naitik_ShahSky_Forest_[2].jpeg"
  },
  {
    "slug": "omkarakshar-l28",
    "key": "OmkarAkshar",
    "title": "Omkar Akshar",
    "orientation": "landscape",
    "width": 7004,
    "height": 4669,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJYwCdAD7AmfK5JMAAP7ClqksxaPgq2fOD9qwwqu7/jeElD8FjRMV1EDBm+ldQ+afbVxl7yET1xaf+852C5bB5BKrGvLAAAA=",
    "source": "photos/landscape/031_OmkarAkshar.jpg"
  },
  {
    "slug": "shyam-nivas-monisha-mistry-l29",
    "key": "Shyam_Nivas_Monisha_Mistry",
    "title": "Shyam Nivas Monisha Mistry",
    "orientation": "landscape",
    "width": 4608,
    "height": 3072,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAQCdASoQAAsAA4BaJZQAApNK2Gd4IAD+qdPyj5jzDGcB0eGUjDfkDaNE9IBszOoynMFax8PDMr8A7kp1ErlSO5fdf8cUr1m256vnjAoAAA==",
    "source": "photos/landscape/032_Shyam_Nivas_Monisha_Mistry.jpg"
  },
  {
    "slug": "3mindperspectivelodha-m-l30",
    "key": "3mindperspectiveLodha_M",
    "title": "3mindperspective Lodha M",
    "orientation": "landscape",
    "width": 7004,
    "height": 4669,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAA4BaJZACdAD1eLndqQOwAAD+0k8bNXNHrDQviHOCrsrFXC0A6ng/uBZZfJFPh2VJhDBXG3pfdWNhl0wGQ7xJCcbzJ9HU0E67pvXc3h1lpCwAAA==",
    "source": "photos/landscape/033_3mindperspectiveLodha_M.jpg"
  },
  {
    "slug": "78-designsmahim-l31",
    "key": "78_DesignsMahim",
    "title": "78 Designs Mahim",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQAgCdASoQAAsAA4BaJYgCdAYvDK9FSuCAAP71PwyvLm8Yq84z7OaJwPacSeYSMqpC668IHdxfBs1mABTyZvDTLU7zgR8WzztknnXLKQ/WIr9dyTVayY8lUJVGoRQu42ExIAAA",
    "source": "photos/landscape/034_78_DesignsMahim.jpg"
  },
  {
    "slug": "prachiborivali-l32",
    "key": "PrachiBorivali",
    "title": "Prachi Borivali",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAsAA4BaJQBOgB9r//4bVAD+wGrDy2sKjzATF8c/+6YJ1by94Hg7roz64eZEnXDFOXN9iM68MrmGtzza9l40sE++B/TCB+nswRtrCjANyviAAAA=",
    "source": "photos/landscape/035_PrachiBorivali.jpg"
  },
  {
    "slug": "rahulthane-l33",
    "key": "RahulThane",
    "title": "Rahul Thane",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwAgCdASoQAAsAA4BaJYwC7AYwx2ya0KFFGzwAAP7YIVT3+ZJPfjmoubo9TFS02tftk2vhU8/RMvsTqI7awQTqv2WGi0fNb6PVD2aIbXm/o60JyWanzBLcw0p/0hgxqZoeetoyuAA=",
    "source": "photos/landscape/036_RahulThane.jpg"
  },
  {
    "slug": "zorkoborivali-l34",
    "key": "ZorkoBorivali",
    "title": "Zorko Borivali",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwAgCdASoQAAsAA4BaJbACdAEK+FgZnmV68AD+eTFi+0CUbSDDH4KpAxtB6Z7yxTJ8ICnEugk0zx3ugC5vRjSZBKBhZ4zgzpsIPdoEsUrPJCm3v5IXSsUzNRpNAwFjS2eViVvuHRxgAA==",
    "source": "photos/landscape/037_ZorkoBorivali.jpg"
  },
  {
    "slug": "zrl-designs-l35",
    "key": "ZRL_Designs",
    "title": "ZRL Designs",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAsAA4BaJZgCdADHc6PHtOAA/rEGAcrtmC9cspaOc/FlNX7FFRaVZtKHz8yAhr+up7XJ/8pzda9S7SD+vYTj3vG31+iPHbUN8l0Lfu1pxJSChaY+usAA",
    "source": "photos/landscape/038_ZRL_Designs.jpg"
  },
  {
    "slug": "hk-architectsparinee-11-west-l36",
    "key": "HK_ArchitectsParinee_11_West",
    "title": "HK Architects Parinee 11 West",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAsAA4BaJZACdACb52PygAD+Sd1xHDjUHdISrSU/7nSHOFRk3EVspLMRQmmT1Wi4eo2O1Puknmm6aMTfzQOVZxN51AyCoIuaVoGkGSLMTHo/CUvHn2JeAAAAAA==",
    "source": "photos/landscape/039_HK_ArchitectsParinee_11_West.jpg"
  },
  {
    "slug": "rashikohinoor-altissimo-l37",
    "key": "RashiKohinoor_Altissimo",
    "title": "Rashi Kohinoor Altissimo",
    "orientation": "landscape",
    "width": 7008,
    "height": 4672,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAsAA4BaJZQAAsdhURpDDXAA/lWxUe4TcOZf+nb7Ai/hG/GgPBFdK+QFnEFtccwvAVo9VWu0LvrfdpPIUIAA",
    "source": "photos/landscape/040_RashiKohinoor_Altissimo.jpg"
  },
  {
    "slug": "muktaclinic-l38",
    "key": "MuktaClinic",
    "title": "Mukta Clinic",
    "orientation": "landscape",
    "width": 5976,
    "height": 3984,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAsAA4BaJaACdH8AGMYSuSAQAAD+VWbNq8bKo3MHbh53Xf8nEVoPZ0gXURUIs/rzKOdB3jksZ02hCrTyz9ed7C7D0eMPngAAAA==",
    "source": "photos/landscape/041_MuktaClinic.jpg"
  },
  {
    "slug": "omkarhema-waghle-l39",
    "key": "OmkarHema_Waghle",
    "title": "Omkar Hema Waghle",
    "orientation": "landscape",
    "width": 5988,
    "height": 3992,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAA4BaJbACdAED/J/eqd9AAAD8GA1b8hL0uSKDTcF6b+JGDPV4PyifvbSOoPOFplFycBssc7r/3YQiUSKof+M8OjYdrDZazmqIA1oyaG414r4AAA==",
    "source": "photos/landscape/042_OmkarHema_Waghle.jpg"
  },
  {
    "slug": "dorityoberoi-l40",
    "key": "DorityOberoi",
    "title": "Dority Oberoi",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAsAA4BaJQBfnBjbVlXLZ4AA9r+6MO3jVE/0OrSLX1bSKIycz3MBK21NmFpmDflC4kNlKGX2d67xKvAwpjtcOSLKNAS7C8/sRwXbi0AAAA==",
    "source": "photos/landscape/043_DorityOberoi.jpg"
  },
  {
    "slug": "hk-architectsshreeji-tower-l41",
    "key": "HK_ArchitectsShreeji_Tower",
    "title": "HK Architects Shreeji Tower",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAsAA4BaJZQCdAC9QEMD2wAA/rNELoc0xPMa8ujtyDQzR0Up6cLOM2Wom+f7iTDXmKZFYaEfC8WBUn3qn+vBFkAAAA==",
    "source": "photos/landscape/044_HK_ArchitectsShreeji_Tower.jpg"
  },
  {
    "slug": "anupam-studiotdh-l42",
    "key": "Anupam_StudioTDH",
    "title": "Anupam Studio TDH",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQAAsAA4BaJYwCdAfwBVEk5c2GgYAA/opnc6Eptpi+sJ6Y35Rlw383/cwWgW2+s7kYz1YDmb+3WYkkfyCALAI2G6qaDPk+kL8i5fTn99YJ0dXkwXttPIgayYAAAA==",
    "source": "photos/landscape/045_Anupam_StudioTDH.jpg"
  },
  {
    "slug": "aura-ids-l43",
    "key": "Aura_IDS",
    "title": "Aura IDS",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAsAA4BaJQBOgBcFscQ8QAD8138YasGzCWAVuKojXtIXBcGhF9h4EJCHore1Lbw9yFzXu9eIg7I+41AFh7v6hxexTMLvqNzNrCcYAAA=",
    "source": "photos/landscape/046_Aura_IDS.jpg"
  },
  {
    "slug": "naksh-design-studio-l44",
    "key": "Naksh_Design_Studio",
    "title": "Naksh Design Studio",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAsAA4BaJZgCdAEXew0bJsxJAAD8xHPgBL2kWQcnJ/tTQTHBNnRWAuWTG73r2HxDtR1BcF98oWzY3dUex/XXZ/yfwtQwBJGG5T4kAAA=",
    "source": "photos/landscape/047_Naksh_Design_Studio.jpg"
  },
  {
    "slug": "adndkalpatru-l45",
    "key": "ADNDKalpatru",
    "title": "ADNDKalpatru",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAsAA4BaJYwCdAEKy6KoVl0wAAD+uBMk/R6oUVwuwx7kvF+n1ECDFuoPaI5p7mjYNUWBB/KSU8IrXDeBNgzghKDU7DmAAAA=",
    "source": "photos/landscape/048_ADNDKalpatru.jpg"
  },
  {
    "slug": "govindhamvinay-l46",
    "key": "GovindhamVinay",
    "title": "Govindham Vinay",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQAAsAA4BaJYgCsADG4rIAkAAA/vb4crrpCC+bPhIMGrP5wqT246USqxE7kdQV0JXGsaUd6FTHIk0CWSRlkyuUcry1REydqMrkAAAA",
    "source": "photos/landscape/050_GovindhamVinay.jpg"
  },
  {
    "slug": "oberoidesign-hue-l47",
    "key": "OberoiDesign_Hue",
    "title": "Oberoi Design Hue",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoQAAsAA4BaJZwAApc6pQAA/taxkV2j4hfu1mD+n72dzILcLtLqL8++Eq+/7HJ1oVr5iFHBkDbm7GAA",
    "source": "photos/landscape/051_OberoiDesign_Hue.jpg"
  },
  {
    "slug": "crescent-baytdh-l48",
    "key": "Crescent_BayTDH",
    "title": "Crescent Bay TDH",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJZQCdAEYES+C16BQAP40aJfPPkcPebYsV8F1wTEqJqPOYZUvt/UZ53U5THXK1qhRGeOpo6hlBb1Eu2lhv8PkDDvOSpEDYAA=",
    "source": "photos/landscape/052_Crescent_BayTDH.jpg"
  },
  {
    "slug": "oberoi-esquire78-design-studio-l49",
    "key": "Oberoi_Esquire78_Design_Studio",
    "title": "Oberoi Esquire78 Design Studio",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAsAA4BaJZQAAwsCfz6+0zWsAAD+9UiJrhodUu7zAXm4y0NhuenUpNRbCDJ+37xsSPyZncm03gzI9P0fewG4h1lAXd6HIAA=",
    "source": "photos/landscape/053_Oberoi_Esquire78_Design_Studio.jpg"
  },
  {
    "slug": "yaffa-skhargar-office-l50",
    "key": "Yaffa'sKhargar_Office",
    "title": "Yaffa's Khargar Office",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJYwAAp/NEhtM5weAAOGV2vFUwouKAzT3MZ9B1GL9QBeoo//EZJeYnNbs8ry9uYTOEZlz9WdwgHZrGb99NTymc9RAJmXWJRkwNGnt8Izb4oJgAAA=",
    "source": "photos/landscape/054_Yaffa'sKhargar_Office.jpg"
  },
  {
    "slug": "elysian-dsgodrej-l51",
    "key": "Elysian_DSGodrej",
    "title": "Elysian DSGodrej",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQAgCdASoQAAsAA4BaJagCdAYvNal/oeaU2QAA+Sps7La0/25oGfUc0MWd8cYMiDArJSYT7ju881+LkY0NcPqb3IpQyEm049EhQTVbC/3tH/vDbymz9pX8Pn2yDGj08VxltOasXH6lq9QwAAA=",
    "source": "photos/landscape/055_Elysian_DSGodrej.jpg"
  },
  {
    "slug": "dority-savana-l52",
    "key": "Dority_Savana",
    "title": "Dority Savana",
    "orientation": "landscape",
    "width": 6000,
    "height": 4000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwAgCdASoQAAsAA4BaJZQCxC8AgqyR4x5ahNwAAP4xTzWA190R24bopJ1j6KpHtaWR5IEKcfiSkX9a4VsD8nDeWzD/ljBp3rgoXaWJ7JePRDWZcRnP95W+M8xPD9sIAAA=",
    "source": "photos/landscape/056_Dority_Savana.jpg"
  },
  {
    "slug": "unattributed-1-l53",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAsAA4BaJZACdAD6mXY410eAAP5NFJqwIVFhTvXl/MoXAyybd6ZP1W9LsZOhlu/HzeX/YfVuYsm2W+IeKe+fhKvwF+FYU+txhqH2N4Td2Xfgd5FNpm9mAAA=",
    "source": "photos/landscape/1.JPG"
  },
  {
    "slug": "unattributed-12-l54",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 7002,
    "height": 4668,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAsAA4BaJZQC7AYvXK964WgYAAD+ieYDTsaoHbxcO8YvfnWZ2jrJH75UQtGw8ZFyW4+lwspLYC/gaWK2CfZW2+g5/1naIGITkoBC1257n2PEgjhYeAAA",
    "source": "photos/landscape/12.jpg"
  },
  {
    "slug": "unattributed-gam00244-l55",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6000,
    "height": 3376,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAkAA4BaJZAC7ADbnJ0JCAD+YRe19zg8x7e8bQrvWle+v3Mfd5s/ymUNdMQ26cGxjb7hXe6Ay/XedG1LVKtz51Z6t6B6qxmCD/ur1qFrnAAA",
    "source": "photos/landscape/GAM00244.jpg"
  },
  {
    "slug": "unattributed-img-2626-l56",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "landscape",
    "width": 6124,
    "height": 4082,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQAAsAA4BaJbACdADWqKp0lgAA/qyWolYZ1KIqbTi1kU4j1XJAZdiAnVVS/Rca6nWXms+fPeydERvQi/M0DQ1lxy180Bxh2roaREaZPqtcHLm4BQuhAezfRQAAAA==",
    "source": "photos/landscape/IMG_2626.JPG"
  },
  {
    "slug": "bombay-cot78-design-p01",
    "key": "bombay_cot78_Design",
    "title": "Bombay Cot78 Design",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZwDImYwmxfpRgu2FDP7OVTVfeAAA/VLW/nnod6/YfB3hdYGsmuOYPfYiWtyqNRWbhQY452zJ3dRWF+uApxEyEa2AUbs2lXfO1jZzYF6+TWDcPOEFlqzed6IgI+Xbb4Zs2OBBKHPEP2wpwejXb6tulye2na0HGiD42uauqla22/RBsqdwtUfr1QSAAA==",
    "source": "photos/portrait/001_bombay_cot78_Design.jpg"
  },
  {
    "slug": "design-hueshome-p02",
    "key": "Design_HuesHome",
    "title": "Design Hues Home",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JZwAAUm9Ito7r1Pwm5cegAP6NP246mzw1nDhc6KyJSPsy2x8jhcsKdbFvZsIKsCO8tn9mbD8cw0kJywgytXJLbB+wSZpOMQxgIZaZK9Ial5feYfH3d4uAAAA=",
    "source": "photos/portrait/002_Design_HuesHome.jpg"
  },
  {
    "slug": "priyadahaus-p03",
    "key": "PriyaDahaus",
    "title": "Priya Dahaus",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQAwCdASoQABgAPu1kqU2ppaOiMAgBMB2JYwDE2GleyoY7hmOhw+gA/vunKLg7IpJUe5f9T4zOc5a37XhnQNmKyietiDirwTM2pjtVYBfaexvykytIxz0GGiL0SUnKvOfFhMc2o5l9wQY6T0DvKRJ0/fqQ2t3WsJZte6kPSqZCWQAA",
    "source": "photos/portrait/003_PriyaDahaus.jpg"
  },
  {
    "slug": "kea-design-labdahisar-p04",
    "key": "KEA_Design_LabDahisar",
    "title": "KEA Design Lab Dahisar",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOkDgAt235LYuwi8rqAAP7JcXiAN8U1J3eUaHNZP7PY/KohftZJeGe3jPaURTb7J5SQe8lAONk+tSIShfjlbA3R8bigDWF6K3xslmtcK444baDCO71k1f6e2qktlLp1lMRPjMMidAI9YfD3T2WKNexPvuPFlYVZfMd51RSsqa0yhrz35aYqtXVdk6hVV+WcOgoapha5IAAA",
    "source": "photos/portrait/004_KEA_Design_LabDahisar.jpg"
  },
  {
    "slug": "omkar-beaumonte-p05",
    "key": "Omkar_Beaumonte",
    "title": "Omkar Beaumonte",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoQABgAPu1kqk4ppaQiMAgBMB2JYwCo9CHe72ILtsQ5owqAAP7jC5Sfx9xkuHGJEmhkdMU065+UZRB0ouLTVm+eJm5yX88nxi4+eb6DaDKTxfzIwTbBUhVsZMAAAA==",
    "source": "photos/portrait/005_Omkar_Beaumonte.jpg"
  },
  {
    "slug": "arzoo-jain2bhk-p06",
    "key": "Arzoo_Jain2bhk",
    "title": "Arzoo Jain2bhk",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoQABgAPu1iqk4ppaQiMAgBMB2JZQC7ABret68b9mGNPmiAAP7D/ouqCMxIDIPhLLHekS1/rGe7puwNnjWJV++pCGRDX69rcjyt5hdvL2i+olFLg7XSUAvVjcFKtMhDaoAAAA==",
    "source": "photos/portrait/006_Arzoo_Jain2bhk.jpg"
  },
  {
    "slug": "mahimdesign-hive-p07",
    "key": "MahimDesign_Hive",
    "title": "Mahim Design Hive",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYwC7BHAKYAW14HEdsLiBVESTaswAAP7hmEiw+L5j5cEm47BOcuCfRxORka80pypbyv2Aizqx1yhUzfehnUyGbYW3KXmFaIUyH0Y3msS6hRQxpgRI/iWPuaFMYpctO3fNCLiHJaYiihAJk2TM4v9tUWET3kQZ3s3LsPgA",
    "source": "photos/portrait/008_MahimDesign_Hive.jpg"
  },
  {
    "slug": "omkar2bhk-pune-p08",
    "key": "Omkar2bhk_Pune",
    "title": "Omkar2bhk Pune",
    "orientation": "portrait",
    "width": 4672,
    "height": 7008,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JZQCdAB6W6ThbiAnFSSPqFIQA/u6gRVwYnEtbDn5F2Y3GQh6tRpVSOZVStLiXimFEF02y0q7aBel/s3GpuR0T3BwqOpLNUdopBcgf7DBWCdiRvGuJ4nY2M0Rm5+fxDIL1Bfnhnv2ZTRA4AAA=",
    "source": "photos/portrait/009_Omkar2bhk_Pune.tif"
  },
  {
    "slug": "omkarpune-office-p09",
    "key": "OmkarPune_Office",
    "title": "Omkar Pune Office",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZACdOUE4AAjaRFL9pTCCs8/7D0AAzeXk5affTOSNYeG0ws5YM8hEYO4buuGGekRbYHMC+zTAncSzlBjxe2tNzrddeRS0OtNPS2J575IpJm4Dsv7rvqqdLMWmiOPCvNnEUdM3SzpxVUqZ5bAxLTOXRCRFAAAA",
    "source": "photos/portrait/010_OmkarPune_Office.tif"
  },
  {
    "slug": "78-design-studiounicot-p10",
    "key": "78_Design_StudioUnicot",
    "title": "78 Design Studio Unicot",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoQABgAPu1iqU2ppaQiMAgBMB2JQBOmUABElI7H5gUclkeyEAAA/dJYqT98ihWaqWDCaMA2hDuW4LyNgQTySQ2VET739JS0UYBrkMVi8Cb5FHfdAH/1GX4noyLoEyin698FjQSgl44QJvJC9IkxgAQs6gAAAA==",
    "source": "photos/portrait/011_78_Design_StudioUnicot.jpg"
  },
  {
    "slug": "78-design-lodha-p11",
    "key": "78_Design_Lodha",
    "title": "78 Design Lodha",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwBACdASoQABgAPu1kq04ppaQiMAgBMB2JZQC7ACHh9NMq/YUYXZ0oAgAA3idGvvEbKmhPaRavkJeZqmdvnPSTJyW8m7SqlNuxF0jvL2qKnHz8gIsjQYBRKyh9bZLK2f2jWAAA",
    "source": "photos/portrait/012_78_Design_Lodha.jpg"
  },
  {
    "slug": "dorityversova-p12",
    "key": "DorityVersova",
    "title": "Dority Versova",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoQABgAPu1krU2ppaSiMAgBMB2JZACdAB5NolaFs8ajAAD9H4PL49XC9Hq+t+w9bglZ5jPaREJHGsjWbiP6rIQk8RoDBZbKjCuJzNgUfwcM6zqcWGJr58tKgAA=",
    "source": "photos/portrait/013_DorityVersova.jpeg"
  },
  {
    "slug": "naitiklodha-bellisimo-p13",
    "key": "NaitikLodha_Bellisimo",
    "title": "Naitik Lodha Bellisimo",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBbZA0eX4sHlLnHvC25HSAAA4m0gxsXzNhL9tk/Ox6bc7IGof/iTgzAKk5+bbdhx5pQJrEY3Cu8/Bvg4W5STcXO16JHiSTwbBO/5JT5a3WM/PSeWUaordXKskhA9fsOU5n6JO0dshvd61fu/btJ9OwPztkgL3tIAAA==",
    "source": "photos/portrait/014_NaitikLodha_Bellisimo.jpg"
  },
  {
    "slug": "naitik-shahsky-forest-2-p14",
    "key": "Naitik_ShahSky_Forest_[2]",
    "title": "Naitik Shah Sky Forest",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoQABgAPu1mqk2ppaQiMAgBMB2JYgCdAGlwpBq+AyM1YMx8AAD+9qkoXMaF4qKh5rKy6w8J3vpUDDmsTMiX+kcduMmUNywxzaGbS77Ce1SQIzOjdflsoK7xaFtpjtOpRd6vEljqtjn6qd3bWoQvN8alYLfAAA==",
    "source": "photos/portrait/015_Naitik_ShahSky_Forest_[2].jpeg"
  },
  {
    "slug": "sky-forestnaitik-shah-p15",
    "key": "Sky_ForestNaitik_Shah",
    "title": "Sky Forest Naitik Shah",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoQABgAPu1iqk2ppaQiMAgBMB2JYwCdACG+tlKtkBNKAP7ZEUHTIKZRj1WGBkZBLVt4I0NsUHczUpEIxt+vNShWepgpYOkyTBo0BFCqeAA=",
    "source": "photos/portrait/016_Sky_ForestNaitik_Shah.jpg"
  },
  {
    "slug": "omkarakshar-p16",
    "key": "OmkarAkshar",
    "title": "Omkar Akshar",
    "orientation": "portrait",
    "width": 4651,
    "height": 6976,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQBYhiYwYYy+JHvnnNJBeZGa1RJAA/MhQmR3qjke5nCFdYAxliLx/zfrB4+gKKP57OkYWnE/qx4EgKUptCA1NvXluzrAltbxu3RY4UUHi+Wm7GXS87KomVUa9Rux57q8WjqX8YN0TruIUdejTh7NPKWP+Tm4FpqPuk69fbEGTFReHZg5MJVYdhwAAAA==",
    "source": "photos/portrait/017_OmkarAkshar.jpg"
  },
  {
    "slug": "shyam-nivas-monisha-mistry-p17",
    "key": "Shyam_Nivas_Monisha_Mistry",
    "title": "Shyam Nivas Monisha Mistry",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoQABgALrV2u12jqampiYC0SygF2AIeAmH06TQ/WxGsfyiAAP71cOeBEMlXUmo3C2sqiGdMmkEy1WAZ8jnbwqnVDrbUReuSLdjcIVETKmW9Yvn6pj3MUxUo0cXZXa+BJZKSLwTLm4fj2/nkS4/QAA==",
    "source": "photos/portrait/018_Shyam_Nivas_Monisha_Mistry.jpg"
  },
  {
    "slug": "3mindperspectivelodha-m-p18",
    "key": "3mindperspectiveLodha_M",
    "title": "3mindperspective Lodha M",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOmUABNBaQPGQhoMMegAP6rgDxfMVn05XiLCawUBqeo3UY/2n6nazeAGjRUOggpv4YMhE6x/PxuYWev44khwWGAa5RtWL8kNX+FNMFhTwk+btvc4s+c/eAVIrsdSg8+dijsnJLURfm2AYbE5ZAA",
    "source": "photos/portrait/019_3mindperspectiveLodha_M.jpg"
  },
  {
    "slug": "78-designsmahim-p19",
    "key": "78_DesignsMahim",
    "title": "78 Designs Mahim",
    "orientation": "portrait",
    "width": 4672,
    "height": 7008,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoQABgAPu1iqU2ppaQiMAgBMB2JYwCAAAk+blY3qjLfPU3O/LwAAP7U/nBKWNbJsrYxLPF9RWFyqZhtMHKVezvp6MGnPIotenNrDm5B94f3PgU+WFuGYZfmqKZn5p71MfkPkd3TZ3FBZoZ+ikpeLUNkR5MO+XPGwr3dPYphMjpLeSJ1pIAAAA==",
    "source": "photos/portrait/020_78_DesignsMahim.jpg"
  },
  {
    "slug": "prachiborivali-p20",
    "key": "PrachiBorivali",
    "title": "Prachi Borivali",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoQABgAPu1iqk2ppaQiMAgBMB2JZwDLLBuiLDsKB6NdvWOAAP3RQpOHTg6jxLI9ckC2I1som0r1/tvwiUcywSvGN0kD3vQ4hUlXgpE6T17H7GyEl/yceAgZk2KUCwcEhi3nz8AA",
    "source": "photos/portrait/021_PrachiBorivali.jpg"
  },
  {
    "slug": "rahulthane-p21",
    "key": "RahulThane",
    "title": "Rahul Thane",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdMoRwACxky238JIgm6iAeT0WAAPlCfSNIlPK8jAUbeu+ooH6BYk2h4xoS5yokAx/zdVLcVMzQlOi6gnhw8/dyBY7wS1c6v2U2tKJvt/d/pynQYsHhnPbT9nb8Mo8bA1Gc+xXc8PIRo7H24rxk1t3r4GCOaq/RmQwd20uUAAAA",
    "source": "photos/portrait/022_RahulThane.jpg"
  },
  {
    "slug": "tdhkitchen-mahim-p22",
    "key": "TDHKitchen_Mahim",
    "title": "TDHKitchen Mahim",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZQDE2CPM/NUS6i99SeouqoAAy08w90UIoMCrpEPlx5NJqIHqfo0WuE/dK/ySlg01dfnNStT6xVnla12rIWbZFXek1lMVoDQsn2ZhtUwNgIw7FGd154AQD80B5aFN2fmBvH3+NmL1Ry3aUrlDsKW7IDxpgwAA",
    "source": "photos/portrait/023_TDHKitchen_Mahim.jpg"
  },
  {
    "slug": "zorkoborivali-p23",
    "key": "ZorkoBorivali",
    "title": "Zorko Borivali",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JYgCdMoADT4wVDmk7UAD+j4Slx+SIH7i0wO7gKGt5BkrDm9xdXWlOxD6g6UmRstqmIzB+HV+gZdKtnJSv7zXT7hL+DYS7Lkw8A95Yi0pD/hMIAAA=",
    "source": "photos/portrait/024_ZorkoBorivali.jpg"
  },
  {
    "slug": "zrl-designs-p24",
    "key": "ZRL_Designs",
    "title": "ZRL Designs",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABQBACdASoQABgAPu1krU6ppaSiMAgBMB2JZgCdMoADQMUZVxcl9ZuYRx3AAP0Poh9OTHWC7VqkZzcFonH8yfZBbEftePCDbeVynTFOFDmkWK49kHCQMVgDqot6RXK6fY9q3KxFlDZUVmiSbAXBKJ3t0zRnyvxDMOhdxJrMmbR8ivQAAAA=",
    "source": "photos/portrait/025_ZRL_Designs.jpg"
  },
  {
    "slug": "hk-architectsparinee-11-west-p25",
    "key": "HK_ArchitectsParinee_11_West",
    "title": "HK Architects Parinee 11 West",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoQABgAPu1iqk4ppaQiMAgBMB2JZQCsAB4WuiZomh1M2QAA/gmPIiG2sm1i3VGpwHaP99ToESdxJ5bXCd16urLGoef1C/HxFiONE71+X3NSs9nvaIjxPNzlbqqeHgpcoLShJZIAAAA=",
    "source": "photos/portrait/026_HK_ArchitectsParinee_11_West.jpg"
  },
  {
    "slug": "rashikohinoor-altissimo-p26",
    "key": "RashiKohinoor_Altissimo",
    "title": "Rashi Kohinoor Altissimo",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADwAwCdASoQABgAPu1kqk4ppaQiMAgBMB2JQBOmUABOjeK4GbFXlrcgAPhZo1amvGWLeUE2Rf9Rys9j4L8+JhhXvkpL3l3S9fBTL2d8RpjBJ/fipFbXRdy7AOS0nX07Q+wn3PpLqHwnZOK9AnmcLBDsbVQ+CoHJbHMl2WDjJBpAAA==",
    "source": "photos/portrait/027_RashiKohinoor_Altissimo.jpg"
  },
  {
    "slug": "muktaclinic-p27",
    "key": "MuktaClinic",
    "title": "Mukta Clinic",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JQBhQBDkJoqvFn020sMAA/otlXaJEu6Y/4TDAEeVIaF7X45zF+Ah1siSmTOYqiYI56+XvtTGkby874iFFJb0kkxv75HF7r56kbAAA",
    "source": "photos/portrait/028_MuktaClinic.jpg"
  },
  {
    "slug": "omkarhema-waghle-p28",
    "key": "OmkarHema_Waghle",
    "title": "Omkar Hema Waghle",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoQABgAPu1kq04ppaQiMAgBMB2JYgAARLwXg18htSFcwAD5nLRPvY70/6gJ+pu/HaFfhMmMjAo4ENv5Bg+0mcuPQzKxABMufDk/fllsgYzUXZeEJtr8HY1QqQn86dQPzAAAAA==",
    "source": "photos/portrait/029_OmkarHema_Waghle.jpg"
  },
  {
    "slug": "dorityoberoi-p29",
    "key": "DorityOberoi",
    "title": "Dority Oberoi",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoQABgAPu1iqU2ppaQiMAgBMB2JZwAAWb8h48rxWuLNNpAA/rO8Tivnlq3z9nH+0257Fq7s7rSoKzsM+tTzrtiUl1EP29WW4FhO+Y+UtUUYbBN86kX0e0ul3jcJnjWtpZBYs7yA0m9XtDfs1uFnfffW6PuWkJFlzpXiugXwz/oeT/d6mAA=",
    "source": "photos/portrait/030_DorityOberoi.jpg"
  },
  {
    "slug": "hk-architectsshreeji-tower-p30",
    "key": "HK_ArchitectsShreeji_Tower",
    "title": "HK Architects Shreeji Tower",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYwC7ACIeXee/JkpvGzM8bgAA/tJLDNjs/frcFRGkUMAHt4/X4F1SxT7JFEMfUYNncdb9EV7LAFb9aqIp3BV2DdawvQ4qqdiC7f4ddasnwsf9YtrWSmqKmOSMVSvwEVwbPLhl8AA=",
    "source": "photos/portrait/031_HK_ArchitectsShreeji_Tower.jpg"
  },
  {
    "slug": "anupam-studiotdh-p31",
    "key": "Anupam_StudioTDH",
    "title": "Anupam Studio TDH",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwBACdASoQABgAPu1kqU4ppaOiMAgBMB2JYgCdLwABz6xWw1++jdl852lqiAD+8qjYv1kOgbb5BU7KHLQDlg+TN5GKe20dWWa9lA9BpNe1SI9PkPGJ+O43j7Vjt1all7fvNFoWej10k0jdYZgvihFp4AA=",
    "source": "photos/portrait/032_Anupam_StudioTDH.jpg"
  },
  {
    "slug": "aura-ids-p32",
    "key": "Aura_IDS",
    "title": "Aura IDS",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOgA4L7WghRJadZOI0gAP4ZoLPEctHfyEerWbZucpGOUWdrSvoQvonzdBfbndUp+LEO4LGSYlkaj92f3J5/2Fkz7VQ8y6rkuleoaGNsYPBdBhZHPRwg1rdBp538FntW8AAA",
    "source": "photos/portrait/033_Aura_IDS.jpg"
  },
  {
    "slug": "naksh-design-studio-p33",
    "key": "Naksh_Design_Studio",
    "title": "Naksh Design Studio",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JaACdMoAKbt+AurPjZAK4D7IAAP79R3v/e6ksn9nV3FAph30Y7kkrWfqiYczJqNOrfoy7J3do60Ql/BA0cN9u1osqnRjWkSF4KYen0wF9tQdnFdfigpuECQDdUa85D9yOI4Ah4oDeY1aI7gAAAA==",
    "source": "photos/portrait/034_Naksh_Design_Studio.jpg"
  },
  {
    "slug": "adndkalpatru-p34",
    "key": "ADNDKalpatru",
    "title": "ADNDKalpatru",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoQABgAPu1kq04ppaQiMAgBMB2JZwDDNBk15efTASrAAAD+w/NAH9blNxjtSEVEH4XGK4/jq29lKfknNRmorlqvXDafIAAA",
    "source": "photos/portrait/035_ADNDKalpatru.jpg"
  },
  {
    "slug": "sumangalnaksh-ds-p35",
    "key": "SumangalNaksh_DS",
    "title": "Sumangal Naksh DS",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYwCdAB9fRa9WI75NPyNyoEAA/qnl9KuXZeX2zdJ05iGvA1gMTrhPPCIIsRMD8/1OJ24KgUuSsMEVayHPVYVTGqm8DGacSWCdoZ+txeHvlkG4Ted48r3cM5uGPxFcP0uaz1bnXj9B8Kf14OalX9SRVUal+MTdi+cKcefmLAAAAA==",
    "source": "photos/portrait/036_SumangalNaksh_DS.jpg"
  },
  {
    "slug": "govindhamvinay-p36",
    "key": "GovindhamVinay",
    "title": "Govindham Vinay",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoQABgAPu1kq04ppaQiMAgBMB2JYwCdMoACKM41tYb0zBfTwADImlGTKvuZU+d958bObhFHRRHQ8BdmzazzrB2t8xbLrwvkz4R858oqAfYjMfTGsLAXu//Cbb/O305EvMeR7xCo1fpnXCAA",
    "source": "photos/portrait/037_GovindhamVinay.jpg"
  },
  {
    "slug": "oberoidesign-hue-p37",
    "key": "OberoiDesign_Hue",
    "title": "Oberoi Design Hue",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAAAQAwCdASoQABgAPu1kqU4ppaOiMAgBMB2JaQAASn12JAAA/f3+qYOCadcR4cAA",
    "source": "photos/portrait/038_OberoiDesign_Hue.jpg"
  },
  {
    "slug": "crescent-baytdh-p38",
    "key": "Crescent_BayTDH",
    "title": "Crescent Bay TDH",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoQABgAPu1yrU+pp6QiMAgBMB2JZABTAAeiIbhhOU1jGDUPQAD+7UNRSecu2mvPcz2yHF2av1t6/HtaS7+i6h58Gk3B5JNvCDa/XzuNKKLTb870AAA=",
    "source": "photos/portrait/039_Crescent_BayTDH.jpg"
  },
  {
    "slug": "oberoi-esquire78-design-studio-p39",
    "key": "Oberoi_Esquire78_Design_Studio",
    "title": "Oberoi Esquire78 Design Studio",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZgCdMoADZS8+bZQRnCqQmpAA+5qGYMbGLa9K2GhAfExT1F+xm302ZEcLJS4JzgKsRQN4DP5K3MNGSqOd4aZgICqpyReH0w+X5gFsIPE5UZyGwHWFe+ap20B5W0pHEWdBro86UoOU+0ECH5gaD1kxRnOgAA==",
    "source": "photos/portrait/040_Oberoi_Esquire78_Design_Studio.jpg"
  },
  {
    "slug": "elysian-dsgodrej-p40",
    "key": "Elysian_DSGodrej",
    "title": "Elysian DSGodrej",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZACdMoADZAee2WVHusy4Rp0/mAD96lKYYMUtElVHU7pGm+9SZLo7Esu5+nVQeVkSCb/gD12JmMaAGIjU6iUGJcZHBHfoqj92JwkZ+IZCs+dQl4SP4O5RfZ2dBVWQE0bGkH4DurdZlKZaXHj6gyveUiyVwzhgQESRnAa7d7A6azyBIUXxiecL7bT7B9c2aB8mSAAA",
    "source": "photos/portrait/041_Elysian_DSGodrej.jpg"
  },
  {
    "slug": "dority-savana-p41",
    "key": "Dority_Savana",
    "title": "Dority Savana",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYwC3uCP6ELPJ83QZfy2yATCAAP6JkRc2u2MfcbrVT8L5+VEwDufXPrjAI6r+bUcmsvYBaExQF5nwa3yN0S+U+9PxBZtoFbWja7Sl9oiOsUxkFkMJ47a+xJjI1TAA",
    "source": "photos/portrait/042_Dority_Savana.jpg"
  },
  {
    "slug": "grahamwestar-p42",
    "key": "GrahamWestar",
    "title": "Graham Westar",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAACwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JZAC07aglANo4VxsX9mjAecE9KPSgAP7pImbI8QPldAvhTle/oOnj2/Hj35+d/S5OdPHZdPnadbLMxyKs7jhLzXzFxSWeMKNHkZ1KrlPIp6ED2JxKS/lCne5fbdc7PvTYMYngu53D55bvu8/nj2IXhb6jx+FwyukJj/wchkkvdlmIjBe8HP+lloC9hUJtQc14GdB0L9OPCVblF1EJ98rpu+fgAA==",
    "source": "photos/portrait/043_GrahamWestar.jpg"
  },
  {
    "slug": "vinayallure-p43",
    "key": "VinayAllure",
    "title": "Vinay Allure",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYgCw7BCS68TjJ6h3tcCOAAD7cldQfxPLjH/Up6V1Alnzk2NLBJ+fHnpbkJqiQAS0JgyurRlhR09brZ481BRfGm5ZVfViUjlBaqWV0eQFH2g/pdCwBXbjHfBzELrIyabVtjHStvAAAA==",
    "source": "photos/portrait/044_VinayAllure.jpg"
  },
  {
    "slug": "prachi-shahbellevue-p44",
    "key": "Prachi_ShahBellevue",
    "title": "Prachi Shah Bellevue",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAACwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JagCdMoRwAdAQ9Lt/wtBoFtZh2AyAAM0QDACCOfAx8+RZs+gongjcPUAuNTk9rr702iFp11I1RIDrWg2R6AJIynINL9Je0OPJLBevToIUB+/XaMxxTvWFsZO+bN+rY8kA1T/SV8m/nPz7su9h52sEIB1RFXZM1mB2ie3l9FuDUTWcidcjZAAA",
    "source": "photos/portrait/045_Prachi_ShahBellevue.jpg"
  },
  {
    "slug": "shrutiandheri-p45",
    "key": "ShrutiAndheri",
    "title": "Shruti Andheri",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADwAwCdASoQABgAPu1iqU2ppaOiMAgBMB2JQBOgBDbYzepatSPcjlAwAP7I5iDIqOnCPPHJ2o+t9ajUnRadYIbDt3vQYBsi/8dxfpfiu7bgj4rMdL9wUlWL7bGwdC+p6cbXiZYqbIWr8tz3rz/E47zwn2iNpKsiIO9IQrdzVfmOKdkepVP7AqjIGAAAAA==",
    "source": "photos/portrait/046_ShrutiAndheri.jpg"
  },
  {
    "slug": "zrldadar-p46",
    "key": "ZRLDadar",
    "title": "ZRLDadar",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoQABgAPu1mq04ppaQiMAgBMB2JQBYdgxjyNfDtF5abNHl1YAD+w+GJJwrOBnbE5smFRyr7edHheM+l6yKqD58I92kRH2tDQnp1GEfxRufrP/nHhJwDGhwYb0TnRAbSlyJI0WsMCeNCqniWy25xgAAA",
    "source": "photos/portrait/047_ZRLDadar.jpg"
  },
  {
    "slug": "zaradadar-2-p47",
    "key": "ZaraDadar_2",
    "title": "Zara Dadar 2",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoQABgAPu1kqU2ppaOiMAgBMB2JYwC/OBR9ZzKQOwF2ZlB4YCIAAP5KdVyRlxciuUHNSj+FIeE56VMxXEqQTi+DHYed1djOVbbhDXvL4kOA8Phn1XMDzj+1R8PynC+5TRFyWRCp7wE3ooUj+5ErSUvmeuwkhb4Ma7klK3yGr2Qe6EQRtESOQIzL67iZf6J3zjKMh3pQlCEviqAA",
    "source": "photos/portrait/048_ZaraDadar_2.jpg"
  },
  {
    "slug": "maneka-lodha-world-view-p48",
    "key": "Maneka_Lodha_World_View",
    "title": "Maneka Lodha World View",
    "orientation": "portrait",
    "width": 4672,
    "height": 7008,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQBACdASoQABgAPu1kqU2ppaOiMAgBMB2JbAC7LwABo+okaeYZlzrcAAD+8TvbwbLkehICxk4fgHpuhuzEXkuK87ZW0qs8im9qIflPe9IrVgUcyJr+C2h1gIzAxJVAAAA=",
    "source": "photos/portrait/049_Maneka_Lodha_World_View.jpg"
  },
  {
    "slug": "smridhioberoi-spelnder-p49",
    "key": "SmridhiOberoi_Spelnder",
    "title": "Smridhi Oberoi Spelnder",
    "orientation": "portrait",
    "width": 4082,
    "height": 6124,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBACdASoQABgAPu1iqU2ppaQiMAgBMB2JQBOgAx7LdM9faqc1pXOXAAD+yqmrxE6FTvNXT6MzFg55WSqoE2fHVQgP4ojmocmfaDUi8DHKd2jmEnvlyrI18pXL9jblt4urpEgcEHNtgW4mWwZ3xFnmZkKbC+6MgSc1fyLNTlfQA1Clkggv3WAA",
    "source": "photos/portrait/050_SmridhiOberoi_Spelnder.jpg"
  },
  {
    "slug": "dority-designs-the-urban-home-p50",
    "key": "Dority_Designs_The_Urban_Home",
    "title": "Dority Designs The Urban Home",
    "orientation": "portrait",
    "width": 4082,
    "height": 6124,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQBACdASoQABgAPu1iqU2ppaQiMAgBMB2JZQC7ACGbKdg6KNY8Rs2YAAD+tNN56hXHJoY1BcQC0m2lxwwks5/kssmEhgOXqSg4n4RAWz4YdJQAAAA=",
    "source": "photos/portrait/051_Dority_Designs_The_Urban_Home.jpg"
  },
  {
    "slug": "design-hueslodha-sterling-p51",
    "key": "Design_huesLodha_Sterling",
    "title": "Design Hues Lodha Sterling",
    "orientation": "portrait",
    "width": 4082,
    "height": 6124,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JQAECAFp7UR/PFHfnDeT8GtrAAP7TiHbySoro66CwZov7jC1G1OHzXbD1j6E+TLHHMU0dEa/EbU/BQIsqp1g/N2w4k9xZWzOy68xV5agqntzW6vNLuz7/1smG/VDriqRU9wMkZFpfJP2v1U3JlwymBZ/bf4Xb7ai5brj+njbHnuAUFtMjegAA",
    "source": "photos/portrait/052_Design_huesLodha_Sterling.jpg"
  },
  {
    "slug": "aarshyaatelier-bunglow-lonavla-p52",
    "key": "Aarshyaatelier_Bunglow_Lonavla",
    "title": "Aarshyaatelier Bunglow Lonavla",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACQBACdASoQABgAPu1orU2ppqSiMAgBMB2JQAB8q0HCbBM7d9I+Q7X89Baf6fAA/vJNDUBBqH+yeWiMDrZ4mnngtrM93LZ35F0YeA8DWrEDABOxP4d2D/gR6xuPgsNPvNrmV7lITIMn8o1PhlG7z2OeJi6wjA+A62dmzprNg5ekZ/RVfgnP4jia17RskOCecKZENLTxUdpDB8Yovsn9HsI2u+sS2k4VqAA=",
    "source": "photos/portrait/053_Aarshyaatelier_Bunglow_Lonavla.jpg"
  },
  {
    "slug": "sagar-gala-designsghatkopar-2bhk-p53",
    "key": "Sagar_Gala_DesignsGhatkopar_2bhk",
    "title": "Sagar Gala Designs Ghatkopar 2bhk",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBACdASoQABgAPu1iqk2ppaQiMAgBMB2JYgCw7CFmMI3oPKGA6YFAC4AA/vN1Ic4X1HykoNGVUwM0rD1hNmojDOz1DoxasX8lp2pQh8JmYb8/0emJNR5f0yOW7LWNq15B+7DO44ZMR+WOwu5Bl8h0boi2LAWzDN9+fxL/gEdUmp+YI8AP0gmjHQpYpPsLuoBmcFqVUMAAAA==",
    "source": "photos/portrait/054_Sagar_Gala_DesignsGhatkopar_2bhk.jpg"
  },
  {
    "slug": "clay-house-design2bhk-residential-p54",
    "key": "Clay_House_Design2BHK_residential",
    "title": "Clay House Design2 BHK Residential",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoQABgAPu1iqU2ppaOiMAgBMB2JbACdACKGpVlkd+jNbealGTgA/vHROWKoGUVasQlHk0j3MdQ+msmsCZ0bf0PSqoearvpVsJtRFu2cEb97QuG2ductWLELHNqkASoc9Y3NHx4wm47+IPSPZgxo2m98/ighalF7AAA=",
    "source": "photos/portrait/055_Clay_House_Design2BHK_residential.jpg"
  },
  {
    "slug": "unattributed-img-2629-p55",
    "key": "unattributed",
    "title": "Unattributed",
    "orientation": "portrait",
    "width": 4000,
    "height": 6000,
    "widths": [
      640,
      1280,
      1920,
      2560
    ],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JagCdMoRwABwAonmiIM6jhVtAAPwBGs4UFtIGO3tAl5ZFnIP/2u3CkjM9zTVcv1zCHrhTU8oRRqn8waGiOkdpSHQgqDbX+n+9wPN8AAA=",
    "source": "photos/portrait/IMG_2629.JPG"
  }
];

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    "key": "Maneka_Lodha_World_View",
    "title": "Maneka Lodha World View",
    "slugs": [
      "maneka-lodha-world-view-l01",
      "maneka-lodha-world-view-p48"
    ]
  },
  {
    "key": "SmridhiOberoi_Spelnder",
    "title": "Smridhi Oberoi Spelnder",
    "slugs": [
      "smridhioberoi-spelnder-l02",
      "smridhioberoi-spelnder-p49"
    ]
  },
  {
    "key": "Aarshyaatelier_Bunglow_Lonavla",
    "title": "Aarshyaatelier Bunglow Lonavla",
    "slugs": [
      "aarshyaatelier-bunglow-lonavla-l03",
      "aarshyaatelier-bunglow-lonavla-p52"
    ]
  },
  {
    "key": "Sagar_Gala_DesignsGhatkopar_2bhk",
    "title": "Sagar Gala Designs Ghatkopar 2bhk",
    "slugs": [
      "sagar-gala-designsghatkopar-2bhk-l04",
      "sagar-gala-designsghatkopar-2bhk-p53"
    ]
  },
  {
    "key": "Clay_House_Design2BHK_residential",
    "title": "Clay House Design2 BHK Residential",
    "slugs": [
      "clay-house-design2bhk-residential-l05",
      "clay-house-design2bhk-residential-p54"
    ]
  },
  {
    "key": "Design_hues3bhkThane",
    "title": "Design Hues3bhk Thane",
    "slugs": [
      "design-hues3bhkthane-l06"
    ]
  },
  {
    "key": "78_DesignsGirgaon3bhk",
    "title": "78 Designs Girgaon3bhk",
    "slugs": [
      "78-designsgirgaon3bhk-l07"
    ]
  },
  {
    "key": "KinjalLonavla",
    "title": "Kinjal Lonavla",
    "slugs": [
      "kinjallonavla-l08"
    ]
  },
  {
    "key": "Home_Maneka_Thapar_Designs",
    "title": "Home Maneka Thapar Designs",
    "slugs": [
      "home-maneka-thapar-designs-l09"
    ]
  },
  {
    "key": "KrishikaUrvashi",
    "title": "Krishika Urvashi",
    "slugs": [
      "krishikaurvashi-l10"
    ]
  },
  {
    "key": "SakshiPepperMoney",
    "title": "Sakshi Pepper Money",
    "slugs": [
      "sakshipeppermoney-l11"
    ]
  },
  {
    "key": "omkarsalon",
    "title": "Omkarsalon",
    "slugs": [
      "omkarsalon-l12"
    ]
  },
  {
    "key": "claydeepak_jyoti",
    "title": "Claydeepak Jyoti",
    "slugs": [
      "claydeepak-jyoti-l13"
    ]
  },
  {
    "key": "bombay_cot78_Design",
    "title": "Bombay Cot78 Design",
    "slugs": [
      "bombay-cot78-design-l14",
      "bombay-cot78-design-p01"
    ]
  },
  {
    "key": "Design_HuesHome",
    "title": "Design Hues Home",
    "slugs": [
      "design-hueshome-l15",
      "design-hueshome-p02"
    ]
  },
  {
    "key": "PriyaDahaus",
    "title": "Priya Dahaus",
    "slugs": [
      "priyadahaus-l16",
      "priyadahaus-p03"
    ]
  },
  {
    "key": "KEA_Design_LabDahisar",
    "title": "KEA Design Lab Dahisar",
    "slugs": [
      "kea-design-labdahisar-l17",
      "kea-design-labdahisar-p04"
    ]
  },
  {
    "key": "Omkar_Beaumonte",
    "title": "Omkar Beaumonte",
    "slugs": [
      "omkar-beaumonte-l18",
      "omkar-beaumonte-p05"
    ]
  },
  {
    "key": "Arzoo_Jain2bhk",
    "title": "Arzoo Jain2bhk",
    "slugs": [
      "arzoo-jain2bhk-l19",
      "arzoo-jain2bhk-p06"
    ]
  },
  {
    "key": "MahimDesign_Hive",
    "title": "Mahim Design Hive",
    "slugs": [
      "mahimdesign-hive-l20",
      "mahimdesign-hive-p07"
    ]
  },
  {
    "key": "Omkar2bhk_Pune",
    "title": "Omkar2bhk Pune",
    "slugs": [
      "omkar2bhk-pune-l21",
      "omkar2bhk-pune-p08"
    ]
  },
  {
    "key": "OmkarPune_Office",
    "title": "Omkar Pune Office",
    "slugs": [
      "omkarpune-office-l22",
      "omkarpune-office-p09"
    ]
  },
  {
    "key": "78_Design_StudioUnicot",
    "title": "78 Design Studio Unicot",
    "slugs": [
      "78-design-studiounicot-l23",
      "78-design-studiounicot-p10"
    ]
  },
  {
    "key": "78_Design_Lodha",
    "title": "78 Design Lodha",
    "slugs": [
      "78-design-lodha-l24",
      "78-design-lodha-p11"
    ]
  },
  {
    "key": "DorityVersova",
    "title": "Dority Versova",
    "slugs": [
      "dorityversova-l25",
      "dorityversova-p12"
    ]
  },
  {
    "key": "NaitikLodha_Bellisimo",
    "title": "Naitik Lodha Bellisimo",
    "slugs": [
      "naitiklodha-bellisimo-l26",
      "naitiklodha-bellisimo-p13"
    ]
  },
  {
    "key": "Naitik_ShahSky_Forest_[2]",
    "title": "Naitik Shah Sky Forest",
    "slugs": [
      "naitik-shahsky-forest-2-l27",
      "naitik-shahsky-forest-2-p14"
    ]
  },
  {
    "key": "OmkarAkshar",
    "title": "Omkar Akshar",
    "slugs": [
      "omkarakshar-l28",
      "omkarakshar-p16"
    ]
  },
  {
    "key": "Shyam_Nivas_Monisha_Mistry",
    "title": "Shyam Nivas Monisha Mistry",
    "slugs": [
      "shyam-nivas-monisha-mistry-l29",
      "shyam-nivas-monisha-mistry-p17"
    ]
  },
  {
    "key": "3mindperspectiveLodha_M",
    "title": "3mindperspective Lodha M",
    "slugs": [
      "3mindperspectivelodha-m-l30",
      "3mindperspectivelodha-m-p18"
    ]
  },
  {
    "key": "78_DesignsMahim",
    "title": "78 Designs Mahim",
    "slugs": [
      "78-designsmahim-l31",
      "78-designsmahim-p19"
    ]
  },
  {
    "key": "PrachiBorivali",
    "title": "Prachi Borivali",
    "slugs": [
      "prachiborivali-l32",
      "prachiborivali-p20"
    ]
  },
  {
    "key": "RahulThane",
    "title": "Rahul Thane",
    "slugs": [
      "rahulthane-l33",
      "rahulthane-p21"
    ]
  },
  {
    "key": "ZorkoBorivali",
    "title": "Zorko Borivali",
    "slugs": [
      "zorkoborivali-l34",
      "zorkoborivali-p23"
    ]
  },
  {
    "key": "ZRL_Designs",
    "title": "ZRL Designs",
    "slugs": [
      "zrl-designs-l35",
      "zrl-designs-p24"
    ]
  },
  {
    "key": "HK_ArchitectsParinee_11_West",
    "title": "HK Architects Parinee 11 West",
    "slugs": [
      "hk-architectsparinee-11-west-l36",
      "hk-architectsparinee-11-west-p25"
    ]
  },
  {
    "key": "RashiKohinoor_Altissimo",
    "title": "Rashi Kohinoor Altissimo",
    "slugs": [
      "rashikohinoor-altissimo-l37",
      "rashikohinoor-altissimo-p26"
    ]
  },
  {
    "key": "MuktaClinic",
    "title": "Mukta Clinic",
    "slugs": [
      "muktaclinic-l38",
      "muktaclinic-p27"
    ]
  },
  {
    "key": "OmkarHema_Waghle",
    "title": "Omkar Hema Waghle",
    "slugs": [
      "omkarhema-waghle-l39",
      "omkarhema-waghle-p28"
    ]
  },
  {
    "key": "DorityOberoi",
    "title": "Dority Oberoi",
    "slugs": [
      "dorityoberoi-l40",
      "dorityoberoi-p29"
    ]
  },
  {
    "key": "HK_ArchitectsShreeji_Tower",
    "title": "HK Architects Shreeji Tower",
    "slugs": [
      "hk-architectsshreeji-tower-l41",
      "hk-architectsshreeji-tower-p30"
    ]
  },
  {
    "key": "Anupam_StudioTDH",
    "title": "Anupam Studio TDH",
    "slugs": [
      "anupam-studiotdh-l42",
      "anupam-studiotdh-p31"
    ]
  },
  {
    "key": "Aura_IDS",
    "title": "Aura IDS",
    "slugs": [
      "aura-ids-l43",
      "aura-ids-p32"
    ]
  },
  {
    "key": "Naksh_Design_Studio",
    "title": "Naksh Design Studio",
    "slugs": [
      "naksh-design-studio-l44",
      "naksh-design-studio-p33"
    ]
  },
  {
    "key": "ADNDKalpatru",
    "title": "ADNDKalpatru",
    "slugs": [
      "adndkalpatru-l45",
      "adndkalpatru-p34"
    ]
  },
  {
    "key": "GovindhamVinay",
    "title": "Govindham Vinay",
    "slugs": [
      "govindhamvinay-l46",
      "govindhamvinay-p36"
    ]
  },
  {
    "key": "OberoiDesign_Hue",
    "title": "Oberoi Design Hue",
    "slugs": [
      "oberoidesign-hue-l47",
      "oberoidesign-hue-p37"
    ]
  },
  {
    "key": "Crescent_BayTDH",
    "title": "Crescent Bay TDH",
    "slugs": [
      "crescent-baytdh-l48",
      "crescent-baytdh-p38"
    ]
  },
  {
    "key": "Oberoi_Esquire78_Design_Studio",
    "title": "Oberoi Esquire78 Design Studio",
    "slugs": [
      "oberoi-esquire78-design-studio-l49",
      "oberoi-esquire78-design-studio-p39"
    ]
  },
  {
    "key": "Yaffa'sKhargar_Office",
    "title": "Yaffa's Khargar Office",
    "slugs": [
      "yaffa-skhargar-office-l50"
    ]
  },
  {
    "key": "Elysian_DSGodrej",
    "title": "Elysian DSGodrej",
    "slugs": [
      "elysian-dsgodrej-l51",
      "elysian-dsgodrej-p40"
    ]
  },
  {
    "key": "Dority_Savana",
    "title": "Dority Savana",
    "slugs": [
      "dority-savana-l52",
      "dority-savana-p41"
    ]
  },
  {
    "key": "unattributed",
    "title": "Unattributed",
    "slugs": [
      "unattributed-1-l53",
      "unattributed-12-l54",
      "unattributed-gam00244-l55",
      "unattributed-img-2626-l56",
      "unattributed-img-2629-p55"
    ]
  },
  {
    "key": "Sky_ForestNaitik_Shah",
    "title": "Sky Forest Naitik Shah",
    "slugs": [
      "sky-forestnaitik-shah-p15"
    ]
  },
  {
    "key": "TDHKitchen_Mahim",
    "title": "TDHKitchen Mahim",
    "slugs": [
      "tdhkitchen-mahim-p22"
    ]
  },
  {
    "key": "SumangalNaksh_DS",
    "title": "Sumangal Naksh DS",
    "slugs": [
      "sumangalnaksh-ds-p35"
    ]
  },
  {
    "key": "GrahamWestar",
    "title": "Graham Westar",
    "slugs": [
      "grahamwestar-p42"
    ]
  },
  {
    "key": "VinayAllure",
    "title": "Vinay Allure",
    "slugs": [
      "vinayallure-p43"
    ]
  },
  {
    "key": "Prachi_ShahBellevue",
    "title": "Prachi Shah Bellevue",
    "slugs": [
      "prachi-shahbellevue-p44"
    ]
  },
  {
    "key": "ShrutiAndheri",
    "title": "Shruti Andheri",
    "slugs": [
      "shrutiandheri-p45"
    ]
  },
  {
    "key": "ZRLDadar",
    "title": "ZRLDadar",
    "slugs": [
      "zrldadar-p46"
    ]
  },
  {
    "key": "ZaraDadar_2",
    "title": "Zara Dadar 2",
    "slugs": [
      "zaradadar-2-p47"
    ]
  },
  {
    "key": "Dority_Designs_The_Urban_Home",
    "title": "Dority Designs The Urban Home",
    "slugs": [
      "dority-designs-the-urban-home-p50"
    ]
  },
  {
    "key": "Design_huesLodha_Sterling",
    "title": "Design Hues Lodha Sterling",
    "slugs": [
      "design-hueslodha-sterling-p51"
    ]
  }
];

/** Every derived title is provisional — see the header. */
export const PORTFOLIO_NEEDS_REVIEW = true;
